// Auto-generated by scripts/build-editor-client.ts and
// scripts/build-dashboard-client.ts — do not edit manually.
// Re-generate: bun run editor-client:build (or dashboard-client:build).
//
// Per-bundle manifest. Content-hashed URLs for the editor + dashboard
// bundles served from the Wrangler [assets] binding. The hash changes
// when the bundle's source changes; identical source produces the same
// hash across builds, so the manifest is byte-stable when source is.

export const EDITOR_CLIENT_MANIFEST = {
  canvasClientUrl: "/_assets/index-j611y859.js",
  canvasStylesUrl: "/_assets/index-zma3fde0.css",
  coEditUrl: "/_assets/co-edit-pgx2fexx.js",
  dashboardClientUrl: "/_assets/dashboard-9xbjjk2w.js",
} as const;
