// src/templates/registry.ts
//
// ADR 0061 Decision 6 — Template Seeds are compositions of Section
// Instance refs, not embedded EditableSites. Each export is now a
// `TemplateSeed` that lists the pool entries the template references;
// `instantiateTemplate(id)` is the function callers use when they need
// an actual `EditableSite` (preview, snapshot, replay).
//
// Section content lives in `src/canvas/section-library/entries/*.json`
// (the pool). The composition references pool rows by their deterministic
// boot-upsert id (`${baseSlug}-v1`). Phase G deletes the whole-template
// JSON fixtures (`home.json`, `enterprise-scale.json`, `apogee-showcase.json`,
// `portfolio-showcase.json`) — the only remaining read of them here is
// the `customStyleKit` for `enterprise-scale-canvas`, `apogee-showcase`,
// and `portfolio-showcase`, which Phase G relocates.

import enterpriseScaleSeed from '../canvas/fixtures/enterprise-scale.json';
import apogeeShowcaseSeed from '../canvas/fixtures/apogee-showcase.json';
import portfolioShowcaseSeed from '../canvas/fixtures/portfolio-showcase.json';
import type {
  LoadExperience,
  MotionSequence,
  RichMotionAsset,
  ScrollScene,
} from '../canvas/behaviour-primitives.js';
import type {
  CanvasPage,
  CanvasSection,
  EditableSite,
  EditableSiteStyleKit,
  StyleKit,
  StyleKitPreset,
} from '../canvas/schema.js';
import {
  SECTION_LIBRARY,
  entryRowId,
  type SectionInstanceRef,
} from '../canvas/section-library/index.js';

/**
 * ADR 0061 Decision 6 — TemplateSeed shape.
 *
 * `pages[*]` mirrors `CanvasPage` except `sections` becomes `bodyRefs`
 * (pointers into the Section Library). `headerRef` / `footerRef` are
 * site-level pinned slots per ADR 0059.
 */
export interface TemplatePage extends Omit<CanvasPage, 'sections'> {
  bodyRefs: SectionInstanceRef[];
}

export interface TemplateSeed {
  id: string;
  name: string;
  tagline: string;
  styleKit: StyleKit;
  customStyleKit?: StyleKitPreset;
  headerRef?: SectionInstanceRef;
  footerRef?: SectionInstanceRef;
  loadExperience?: LoadExperience;
  motionSequences?: MotionSequence[];
  scrollScenes?: ScrollScene[];
  richMotionAssets?: RichMotionAsset[];
  pages: TemplatePage[];
}

// ---------------------------------------------------------------------------
// Section pool resolution
//
// Resolve refs against the entire SECTION_LIBRARY by deterministic
// `${baseSlug}-v${version}` id (Phase B's `entryRowId` shape). A miss is
// a build-time bug — fail loud rather than fall back to a placeholder.

const sectionPoolByRowId = new Map<string, (typeof SECTION_LIBRARY)[number]>();
for (const entry of SECTION_LIBRARY) {
  sectionPoolByRowId.set(entryRowId(entry), entry);
}

function resolveRef(ref: SectionInstanceRef): CanvasSection {
  const entry = sectionPoolByRowId.get(ref.sectionId);
  if (!entry) {
    throw new Error(
      `instantiateTemplate: unresolved section ref '${ref.sectionId}' — pool entry missing. ` +
        `Did you remove a ` +
        `SECTION_LIBRARY` +
        ` entry without updating the composition?`,
    );
  }
  // Deep clone so each instantiation gets a fresh tree; overrides + scope
  // never mutate the shared pool entry.
  const section = JSON.parse(JSON.stringify(entry.sectionData)) as CanvasSection;
  section.instanceScope = ref.instanceId;
  if (ref.overrides) {
    for (const [origId, patch] of Object.entries(ref.overrides)) {
      const el = section.elements.find((e) => e.id === origId);
      if (el) Object.assign(el, patch);
    }
  }
  return section;
}

// ---------------------------------------------------------------------------
// Template compositions
//
// Auto-generated by `scripts/gen-template-compositions.ts` at the Phase D
// rewrite. Hand-editable from here on; re-run the generator only as a
// reference if the underlying pool slugs ever get bulk-renamed.

const ENTERPRISE_KIT = (enterpriseScaleSeed as unknown as { customStyleKit: StyleKitPreset })
  .customStyleKit;
const APOGEE_KIT = (apogeeShowcaseSeed as unknown as { customStyleKit: StyleKitPreset })
  .customStyleKit;
const PORTFOLIO_KIT = (portfolioShowcaseSeed as unknown as { customStyleKit: StyleKitPreset })
  .customStyleKit;

const VELOCITY_KIT: StyleKitPreset = {
  bg: '#111112',
  panel: '#282C20',
  text: '#F4F4ED',
  muted: '#5D6254',
  accent: '#C8FF1A',
  accentText: '#111112',
  fontFamilyDisplay:
    "'Instrument Serif', 'Iowan Old Style', Georgia, 'Times New Roman', serif",
  fontFamilyBody: "'Inter Tight', 'Inter', system-ui, -apple-system, sans-serif",
  fontFamilyMono: "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace",
  headingScale: 1.12,
  bodyScale: 1,
  labelScale: 0.82,
  lineHeight: 1.45,
  radius: '4px',
  borderWidth: '1px',
  shadow: '0 12px 40px rgba(0, 0, 0, 0.45)',
  surfaceVariants: {
    flat: {
      background: '#111112',
      shadow: 'none',
    },
    raised: {
      background: '#282C20',
      border: '1px solid rgba(93, 98, 84, 0.35)',
      shadow: '0 12px 40px rgba(0, 0, 0, 0.45)',
      radius: '6px',
    },
    glass: {
      background: 'rgba(40, 44, 32, 0.72)',
      border: '1px solid rgba(200, 255, 26, 0.18)',
      shadow: '0 8px 28px rgba(0, 0, 0, 0.40)',
      radius: '6px',
    },
    outlined: {
      background: 'transparent',
      border: '1px solid rgba(93, 98, 84, 0.45)',
      radius: '4px',
    },
    sticker: {
      background: '#282C20',
      border: '1px solid rgba(200, 255, 26, 0.35)',
      shadow: '4px 4px 0 #C8FF1A, 0 0 0 1px rgba(200, 255, 26, 0.15)',
      radius: '4px',
    },
    'editorial-frame': {
      background: 'transparent',
      border: '2px solid #C8FF1A',
      radius: '0px',
    },
    'soft-panel': {
      background: '#1a1b1c',
      shadow: '0 1px 0 rgba(244, 244, 237, 0.04) inset',
    },
  },
  shapeFill: '#C8FF1A',
  shapeStroke: '#5D6254',
  shapeStrokeWidth: '1px',
  actionRadius: '999px',
  actionPadding: '14px 24px',
  actionVariants: {
    solid: {
      background: '#C8FF1A',
      color: '#111112',
      weight: 700,
      borderRadius: '999px',
      boxShadow: '0 4px 16px rgba(200, 255, 26, 0.25)',
    },
    outline: {
      background: 'transparent',
      color: '#F4F4ED',
      border: '1px solid rgba(244, 244, 237, 0.35)',
      weight: 600,
      borderRadius: '999px',
    },
    ghost: {
      background: 'transparent',
      color: '#F4F4ED',
      weight: 500,
      borderRadius: '4px',
      padding: '8px 12px',
    },
    pill: {
      background: '#282C20',
      color: '#F4F4ED',
      weight: 600,
      border: '1px solid rgba(93, 98, 84, 0.45)',
      borderRadius: '999px',
      padding: '6px 14px',
      letterSpacing: '0.06em',
    },
    glass: {
      background: 'rgba(40, 44, 32, 0.72)',
      color: '#F4F4ED',
      border: '1px solid rgba(200, 255, 26, 0.20)',
      backdropFilter: 'blur(12px)',
      borderRadius: '999px',
    },
    brutalist: {
      background: '#FF6B2A',
      color: '#111112',
      border: '2px solid #FF6B2A',
      weight: 800,
      borderRadius: '0px',
      boxShadow: '4px 4px 0 #111112',
    },
    underline: {
      background: 'transparent',
      color: '#C8FF1A',
      textDecoration: 'underline',
      borderRadius: '0px',
      padding: '0',
    },
  },
  motionDurationMs: 420,
  motionEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
  motionPresets: {
    none: {},
    'fade-up': {
      transform: 'translateY(16px)',
      opacity: 0,
    },
    'fade-down': {
      transform: 'translateY(-16px)',
      opacity: 0,
    },
    'fade-in': {
      opacity: 0,
    },
    'fade-right': {
      transform: 'translateX(-16px)',
      opacity: 0,
    },
    'slide-left': {
      transform: 'translateX(24px)',
      opacity: 0,
    },
    'slide-up': {
      transform: 'translateY(24px)',
    },
    'slide-right': {
      transform: 'translateX(-24px)',
    },
    'scale-in': {
      transform: 'scale(0.94)',
      opacity: 0,
    },
    'zoom-out': {
      transform: 'scale(1.06)',
      opacity: 0,
    },
    'blur-in': {
      opacity: 0,
    },
    'rotate-in': {
      transform: 'rotate(-3deg) scale(0.96)',
      opacity: 0,
    },
    'flip-in': {
      transform: 'perspective(600px) rotateY(90deg)',
      opacity: 0,
    },
    'bounce-in': {
      transform: 'scale(0.72)',
      opacity: 0,
    },
    'stagger-children': {
      transform: 'translateY(10px)',
      opacity: 0,
      delayMs: 50,
    },
    'slow-drift': {
      transform: 'translateY(0px)',
    },
    'parallax-soft': {
      transform: 'translateY(8px)',
    },
  },
};

export const velocityAthleteTemplate: TemplateSeed = {
  id: 'velocity-athlete',
  name: 'Velocity Athlete',
  tagline: 'A kinetic personal-brand template for athletes, creators, and high-energy product drops.',
  styleKit: 'custom',
  customStyleKit: VELOCITY_KIT,
  headerRef: { sectionId: 'velocity-template-header-v1', instanceId: 'velocityheader' },
  footerRef: { sectionId: 'velocity-template-footer-v1', instanceId: 'velocityfooter' },
  loadExperience: {
    id: 'velocity-load',
    label: 'Ari Vale',
    enterLabel: 'Load Vale',
    background: '#111112',
    foreground: '#C8FF1A',
    handoff: {
      effect: 'mask-open',
      durationMs: 420,
      easing: 'cubic-bezier(.76,0,.24,1)',
    },
    sequenceId: 'velocity-load-sequence',
  },
  richMotionAssets: [
    {
      id: 'velocity-helmet-sequence',
      kind: 'image-sequence',
      posterAssetId: 'seed-velocity-helmet-frame-00',
      alt: 'Abstract signal helmet rotating through a kinetic frame sequence',
      frameAssetIds: [
        'seed-velocity-helmet-frame-00',
        'seed-velocity-helmet-frame-01',
        'seed-velocity-helmet-frame-02',
        'seed-velocity-helmet-frame-03',
        'seed-velocity-helmet-frame-04',
        'seed-velocity-helmet-frame-05',
        'seed-velocity-helmet-frame-06',
        'seed-velocity-helmet-frame-07',
        'seed-velocity-helmet-frame-08',
        'seed-velocity-helmet-frame-09',
        'seed-velocity-helmet-frame-10',
        'seed-velocity-helmet-frame-11',
      ],
      playback: { driver: 'load', fps: 18, loop: true },
    },
  ],
  motionSequences: [
    {
      id: 'velocity-load-sequence',
      trigger: { type: 'load-enter' },
      reducedMotion: 'final-state',
      steps: [
        { id: 'load-out', target: { type: 'site' }, to: { opacity: 1 }, durationMs: 260 },
        {
          id: 'hero-motion-in',
          target: { type: 'element', elementId: 'velocity-hero-motion' },
          from: { scale: 0.88, opacity: 0 },
          to: { scale: 1, opacity: 1 },
          durationMs: 620,
          delayMs: 80,
        },
      ],
    },
    {
      id: 'velocity-impact-split',
      trigger: { type: 'section-enter', sectionId: 'velocity-impact' },
      reducedMotion: 'final-state',
      steps: [
        {
          id: 'impact-words',
          target: { type: 'text-split', elementId: 'velocity-impact-heading', unit: 'word' },
          from: { translateY: 32, opacity: 0 },
          to: { translateY: 0, opacity: 1 },
          durationMs: 420,
          staggerMs: 28,
        },
      ],
    },
    {
      id: 'velocity-story-scrub',
      trigger: { type: 'scroll-scene', scrollSceneId: 'velocity-story-scene' },
      reducedMotion: 'final-state',
      steps: [
        {
          id: 'story-track-x',
          target: { type: 'element', elementId: 'velocity-story-meta' },
          from: { opacity: 0.55 },
          to: { opacity: 1 },
          durationMs: 1,
        },
        {
          id: 'story-meta-mask',
          target: { type: 'text-split', elementId: 'velocity-story-meta', unit: 'word' },
          textEffect: 'mask-reveal',
          from: { opacity: 0 },
          to: { opacity: 1 },
          durationMs: 1,
        },
      ],
    },
  ],
  scrollScenes: [
    {
      id: 'velocity-story-scene',
      sectionId: 'velocity-story',
      sequenceId: 'velocity-story-scrub',
      pinTarget: { type: 'section', sectionId: 'velocity-story' },
      horizontalTrack: { elementId: 'velocity-story-track', distancePx: 940 },
      beforeAfterReveal: {
        beforeElementId: 'velocity-story-track',
        afterElementId: 'velocity-story-meta',
        axis: 'x',
        startProgress: 0.15,
        endProgress: 0.85,
        reducedMotion: 'end',
      },
      startOffsetPx: 0,
      endOffsetPx: 1800,
    },
  ],
  pages: [
    {
      id: 'page-velocity-home',
      slug: 'home',
      title: 'Ari Vale - Velocity Athlete',
      width: 1440,
      pageBackground: '#111112',
      sectionGap: 0,
      bodyRefs: [
        { sectionId: 'velocity-template-hero-v1', instanceId: 'velocityhero' },
        { sectionId: 'velocity-template-impact-v1', instanceId: 'velocityimpact' },
        { sectionId: 'velocity-template-story-v1', instanceId: 'velocitystory' },
        { sectionId: 'velocity-template-artifacts-v1', instanceId: 'velocityartifacts' },
        { sectionId: 'velocity-template-store-v1', instanceId: 'velocitystore' },
      ],
    },
  ],
};

export const starterTemplate: TemplateSeed = {
  id: 'starter-canvas',
  name: 'Starter Canvas',
  tagline:
    'A flexible canvas with editable sections, rich text, media, actions, shapes, surfaces, style kits, and motion.',
  styleKit: 'charcoal',
  headerRef: { sectionId: 'starter-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'starter-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Starter Canvas',
      width: 1440,
      bodyRefs: [
        { sectionId: 'starter-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'starter-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'starter-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const launchTemplate: TemplateSeed = {
  id: 'launch-canvas',
  name: 'Launch Page',
  tagline:
    'A crisp product-launch starting point with a strong hero, proof sections, and a direct CTA.',
  styleKit: 'blue-saas',
  headerRef: { sectionId: 'launch-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'launch-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Launch Page',
      width: 1440,
      bodyRefs: [
        { sectionId: 'launch-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'launch-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'launch-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const enterpriseScaleTemplate: TemplateSeed = {
  id: 'enterprise-scale-canvas',
  name: 'Enterprise Scale',
  tagline:
    'A proof-heavy enterprise landing page seed with governed launch messaging, outcome cards, team sections, scalability, and sales CTAs.',
  styleKit: 'custom',
  customStyleKit: ENTERPRISE_KIT,
  pages: [
    {
      id: 'page-enterprise-scale',
      slug: 'home',
      title: 'Enterprise Scale',
      width: 1440,
      bodyRefs: [
        { sectionId: 'enterprise-template-hero-v1', instanceId: 'enterprisehero' },
        { sectionId: 'enterprise-template-proof-v1', instanceId: 'enterpriseproof' },
        { sectionId: 'enterprise-template-outcomes-v1', instanceId: 'enterpriseoutcomes' },
        { sectionId: 'enterprise-template-teams-v1', instanceId: 'enterpriseteams' },
        { sectionId: 'enterprise-template-scale-v1', instanceId: 'enterprisescale' },
        { sectionId: 'enterprise-template-governance-v1', instanceId: 'enterprisegovernance' },
        { sectionId: 'enterprise-template-success-v1', instanceId: 'enterprisesuccess' },
      ],
    },
  ],
};

export const studioTemplate: TemplateSeed = {
  id: 'studio-canvas',
  name: 'Studio Portfolio',
  tagline:
    'A visual-first portfolio seed for studios, designers, photographers, and independent makers.',
  styleKit: 'orange-editorial',
  headerRef: { sectionId: 'studio-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'studio-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Studio Portfolio',
      width: 1440,
      bodyRefs: [
        { sectionId: 'studio-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'studio-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'studio-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const localTemplate: TemplateSeed = {
  id: 'local-canvas',
  name: 'Local Business',
  tagline:
    'A warm small-business seed for cafes, salons, classes, services, and neighborhood teams.',
  styleKit: 'green-organic',
  headerRef: { sectionId: 'local-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'local-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Local Business',
      width: 1440,
      bodyRefs: [
        { sectionId: 'local-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'local-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'local-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const pressTemplate: TemplateSeed = {
  id: 'press-canvas',
  name: 'Press Canvas',
  tagline:
    'A serif-led editorial canvas for writers, publications, and anyone who still believes a sentence can carry a brand.',
  styleKit: 'ivory-press',
  headerRef: { sectionId: 'press-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'press-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Press Canvas',
      width: 1440,
      bodyRefs: [
        { sectionId: 'press-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'press-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'press-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const violetLaunchTemplate: TemplateSeed = {
  id: 'violet-launch',
  name: 'Violet Launch',
  tagline:
    'A bold midnight launch canvas with electric violet accents — the look indie products take when they want to be noticed.',
  styleKit: 'midnight-violet',
  headerRef: { sectionId: 'violet-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'violet-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Violet Launch',
      width: 1440,
      bodyRefs: [
        { sectionId: 'violet-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'violet-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'violet-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const apogeeShowcaseTemplate: TemplateSeed = {
  id: 'apogee-showcase',
  name: 'Apogee Showcase',
  tagline:
    'A multi-page showcase site — dark, bold, and loaded with every element type. Carousels, charts, forms, code snippets, accordions, embeds, and more.',
  styleKit: 'custom',
  customStyleKit: APOGEE_KIT,
  headerRef: { sectionId: 'apogee-template-header-v1', instanceId: 'wfsiteheader' },
  footerRef: { sectionId: 'apogee-template-footer-v1', instanceId: 'wfsitefooter' },
  pages: [
    {
      id: 'page-wf-home',
      slug: 'index',
      title: 'Apogee - The web platform for modern businesses',
      width: 1440,
      description:
        'Design, build, optimize, and rank in AI search - all in Apogee. Enterprise-grade security, CMS, hosting, and AEO built in.',
      entranceAnimation: 'fade-up',
      scrollTriggerMode: 'on-scroll',
      bodyRefs: [
        { sectionId: 'apogee-template-hero-v1', instanceId: 'wfhero' },
        { sectionId: 'apogee-template-platform-v1', instanceId: 'wfplatform' },
        { sectionId: 'apogee-template-social-proof-v1', instanceId: 'wfsocialproof' },
        { sectionId: 'apogee-template-carousel-showcase-v1', instanceId: 'wfcarouselshowcase' },
        { sectionId: 'apogee-template-features-v1', instanceId: 'wffeatures' },
        { sectionId: 'apogee-template-cta-band-v1', instanceId: 'wfctaband' },
        { sectionId: 'apogee-template-embed-demo-v1', instanceId: 'wfembeddemo' },
      ],
    },
    {
      id: 'page-wf-blog',
      slug: 'blog',
      title: 'Blog - Insights, tutorials, and updates',
      width: 1440,
      description: 'The latest on web design, development, and building for the modern web.',
      entranceAnimation: 'fade-up',
      bodyRefs: [
        { sectionId: 'apogee-template-blog-hero-v1', instanceId: 'wfbloghero' },
        { sectionId: 'apogee-template-blog-featured-v1', instanceId: 'wfblogfeatured' },
        { sectionId: 'apogee-template-blog-collection-v1', instanceId: 'wfblogcollection' },
        { sectionId: 'apogee-template-blog-code-demo-v1', instanceId: 'wfblogcodedemo' },
        { sectionId: 'apogee-template-blog-newsletter-v1', instanceId: 'wfblognewsletter' },
      ],
    },
    {
      id: 'page-wf-pricing',
      slug: 'pricing',
      title: 'Pricing - Plans for every team',
      width: 1440,
      description:
        'Start building for free and add a paid plan later to unlock premium hosting, design, and collaboration features.',
      entranceAnimation: 'fade-up',
      bodyRefs: [
        { sectionId: 'apogee-template-pricing-hero-v1', instanceId: 'wfpricinghero' },
        { sectionId: 'apogee-template-pricing-tiers-v1', instanceId: 'wfpricingtiers' },
        { sectionId: 'apogee-template-pricing-compare-v1', instanceId: 'wfpricingcompare' },
        { sectionId: 'apogee-template-pricing-faq-v1', instanceId: 'wfpricingfaq' },
        { sectionId: 'apogee-template-pricing-chart-v1', instanceId: 'wfpricingchart' },
        { sectionId: 'apogee-template-pricing-cta-v1', instanceId: 'wfpricingcta' },
      ],
    },
    {
      id: 'page-wf-enterprise',
      slug: 'enterprise',
      title: 'Enterprise - Scale with confidence',
      width: 1440,
      description:
        'See how enterprises achieve a 332% ROI with Apogee. Enterprise-grade scalability, security, and support.',
      entranceAnimation: 'scale-in',
      scrollTriggerMode: 'on-scroll',
      bodyRefs: [
        { sectionId: 'apogee-template-ent-hero-v1', instanceId: 'wfenthero' },
        { sectionId: 'apogee-template-ent-pillars-v1', instanceId: 'wfentpillars' },
        { sectionId: 'apogee-template-ent-roi-chart-v1', instanceId: 'wfentroichart' },
        { sectionId: 'apogee-template-ent-demo-embed-v1', instanceId: 'wfentdemoembed' },
        { sectionId: 'apogee-template-ent-contact-form-v1', instanceId: 'wfentcontactform' },
        { sectionId: 'apogee-template-ent-logos-v1', instanceId: 'wfentlogos' },
        { sectionId: 'apogee-template-ent-cta-v1', instanceId: 'wfentcta' },
      ],
    },
    {
      id: 'page-wf-customers',
      slug: 'customers',
      title: 'Customers - Stories from 300,000+ teams',
      width: 1440,
      description:
        'See how enterprises, agencies, and businesses large and small build with Apogee.',
      entranceAnimation: 'fade-up',
      bodyRefs: [
        { sectionId: 'apogee-template-cust-hero-v1', instanceId: 'wfcusthero' },
        { sectionId: 'apogee-template-cust-carousel-v1', instanceId: 'wfcustcarousel' },
        { sectionId: 'apogee-template-cust-grid-v1', instanceId: 'wfcustgrid' },
        { sectionId: 'apogee-template-cust-cta-v1', instanceId: 'wfcustcta' },
      ],
    },
    {
      id: 'page-wf-404',
      slug: '_404',
      title: 'Lost in the wilds — Apogee',
      width: 1440,
      description: "We couldn't find that page. Head back home or browse the latest from Apogee.",
      entranceAnimation: 'fade-up',
      bodyRefs: [{ sectionId: 'apogee-template-404-hero-v1', instanceId: 'wf404hero' }],
    },
  ],
};

export const portfolioShowcaseTemplate: TemplateSeed = {
  id: 'portfolio-showcase',
  name: 'Engineer Portfolio',
  tagline:
    'Dark warm-toned single-page engineer portfolio: hero, tech stack, selected work, and a notes blog with four mock long-form posts that exercise the page-bound collection.',
  styleKit: 'custom',
  customStyleKit: PORTFOLIO_KIT,
  headerRef: { sectionId: 'portfolio-template-header-v1', instanceId: 'pfsiteheader' },
  footerRef: { sectionId: 'portfolio-template-footer-v1', instanceId: 'pfsitefooter' },
  pages: [
    {
      id: 'page-pf-home',
      slug: 'index',
      title: 'Aayushman Singh — Full-Stack Engineer',
      width: 1440,
      description:
        "Full-stack engineer building autonomous agents, developer tools, and production-grade web systems. SIH '24 winner with OSINT work deployed by India's National Investigation Agency.",
      entranceAnimation: 'fade-up',
      scrollTriggerMode: 'on-scroll',
      bodyRefs: [
        { sectionId: 'portfolio-template-hero-v1', instanceId: 'pfhero' },
        { sectionId: 'portfolio-template-explore-v1', instanceId: 'pfexplore' },
      ],
    },
    {
      // ADR 0063 dec 2 + F5 — `pageKind: 'collection-index'` is retired.
      // The Collection element inside the resolved
      // portfolio-template-blog-list section carries `collectionSlug:
      // 'blog'` directly (see the JSON), so this page no longer needs
      // page-level binding metadata. It is now an ordinary CanvasPage
      // whose body happens to include one Collection element bound to
      // the blog source.
      id: 'page-pf-blog',
      slug: 'blog',
      title: 'Notes — Aayushman Singh',
      width: 1440,
      description:
        'Long-form writing on autonomous agents, self-healing CI, local-first software, and building tools for the State.',
      entranceAnimation: 'fade-up',
      bodyRefs: [
        { sectionId: 'portfolio-template-blog-hero-v1', instanceId: 'pfbloghero' },
        { sectionId: 'portfolio-template-blog-list-v1', instanceId: 'pfbloglist' },
      ],
    },
    {
      // ADR 0060 F2 — single template page that materializes per collection
      // entry at publish time. Replaces the pre-F2 hand-authored
      // page-pf-post-* pages (post1..post4) that the portfolio composition
      // had at branch base. Section refs point at the new
      // `portfolio-template-post-tmpl-*` pool entries extracted from the
      // current portfolio-showcase.json fixture.
      id: 'page-pf-post-template',
      slug: 'blog/template',
      title: '{{title}}',
      width: 1440,
      description: '{{excerpt}}',
      locale: 'en',
      pageBackground: '#16140f',
      entranceAnimation: 'fade-up',
      defaultMotionPreset: 'fade-up',
      sectionGap: 0,
      maxWidth: 1440,
      pageKind: 'collection-item-template',
      collectionSlug: 'blog',
      bodyRefs: [
        { sectionId: 'portfolio-template-post-tmpl-hero-v1', instanceId: 'pfposttmplhero' },
        { sectionId: 'portfolio-template-post-tmpl-body-v1', instanceId: 'pfposttmplbody' },
      ],
    },
  ],
};

export const allTemplateSeeds: ReadonlyArray<TemplateSeed> = [
  starterTemplate,
  launchTemplate,
  enterpriseScaleTemplate,
  studioTemplate,
  localTemplate,
  pressTemplate,
  violetLaunchTemplate,
  apogeeShowcaseTemplate,
  portfolioShowcaseTemplate,
  velocityAthleteTemplate,
];

const templatesById = new Map(allTemplateSeeds.map((template) => [template.id, template]));

function cloneTemplateField<T>(value: T | undefined): T | undefined {
  return value === undefined ? undefined : structuredClone(value);
}

export function getTemplateSeed(id: string): TemplateSeed | null {
  return templatesById.get(id) ?? null;
}

/**
 * ADR 0061 Decision 6 — materialise a TemplateSeed composition into a
 * full `EditableSite`. Pages get their `bodyRefs` resolved against the
 * Section Library; header / footer get their refs resolved to the
 * `EditableSite.header` / `.footer` slots; customStyleKit / styleKit
 * pass through. Each materialised section carries `instanceScope` from
 * its ref's `instanceId` so the renderer can surface
 * `data-instance-scope` and Yjs round-trip preserves the binding.
 *
 * Throws on an unknown templateId or an unresolved section ref — both
 * are build-time mistakes, not runtime conditions.
 */
export function instantiateTemplate(templateId: string): EditableSite {
  const seed = templatesById.get(templateId);
  if (!seed) {
    throw new Error(`instantiateTemplate: unknown template id '${templateId}'`);
  }
  let styleKitField: EditableSiteStyleKit;
  if (seed.styleKit === 'custom') {
    if (seed.customStyleKit === undefined) {
      throw new Error(
        `instantiateTemplate: template '${templateId}' has styleKit='custom' but no customStyleKit`,
      );
    }
    styleKitField = { styleKit: 'custom', customStyleKit: seed.customStyleKit };
  } else {
    styleKitField = { styleKit: seed.styleKit };
  }
  const state: EditableSite = {
    ...styleKitField,
    pages: seed.pages.map((p) => {
      const page: CanvasPage = {
        id: p.id,
        slug: p.slug,
        title: p.title,
        width: p.width,
        sections: p.bodyRefs.map(resolveRef),
      };
      if (p.description !== undefined) page.description = p.description;
      if (p.ogImageAssetId !== undefined) page.ogImageAssetId = p.ogImageAssetId;
      if (p.canonical !== undefined) page.canonical = p.canonical;
      if (p.noIndex !== undefined) page.noIndex = p.noIndex;
      if (p.locale !== undefined) page.locale = p.locale;
      if (p.entranceAnimation !== undefined) page.entranceAnimation = p.entranceAnimation;
      if (p.scrollTriggerMode !== undefined) page.scrollTriggerMode = p.scrollTriggerMode;
      if (p.pageBackground !== undefined) page.pageBackground = p.pageBackground;
      if (p.defaultMotionPreset !== undefined) page.defaultMotionPreset = p.defaultMotionPreset;
      if (p.sectionGap !== undefined) page.sectionGap = p.sectionGap;
      if (p.maxWidth !== undefined) page.maxWidth = p.maxWidth;
      if (p.publishedDate !== undefined) page.publishedDate = p.publishedDate;
      if (p.author !== undefined) page.author = p.author;
      if (p.tags !== undefined) page.tags = p.tags;
      if (p.category !== undefined) page.category = p.category;
      if (p.suppressHeader !== undefined) page.suppressHeader = p.suppressHeader;
      if (p.suppressFooter !== undefined) page.suppressFooter = p.suppressFooter;
      if (p.pageKind !== undefined) page.pageKind = p.pageKind;
      if (p.collectionSlug !== undefined) page.collectionSlug = p.collectionSlug;
      return page;
    }),
  };
  if (seed.headerRef) state.header = resolveRef(seed.headerRef);
  if (seed.footerRef) state.footer = resolveRef(seed.footerRef);
  const loadExperience = cloneTemplateField(seed.loadExperience);
  const motionSequences = cloneTemplateField(seed.motionSequences);
  const scrollScenes = cloneTemplateField(seed.scrollScenes);
  const richMotionAssets = cloneTemplateField(seed.richMotionAssets);
  if (loadExperience !== undefined) state.loadExperience = loadExperience;
  if (motionSequences !== undefined) state.motionSequences = motionSequences;
  if (scrollScenes !== undefined) state.scrollScenes = scrollScenes;
  if (richMotionAssets !== undefined) state.richMotionAssets = richMotionAssets;
  return state;
}
