// src/templates/registry.ts
//
// ADR 0061 Decision 6 — Template Seeds are compositions of Section
// Instance refs, not embedded EditableSites. Each export is now a
// `TemplateSeed` that lists the pool entries the template references;
// `instantiateTemplate(id)` is the function callers use when they need
// an actual `EditableSite` (preview, snapshot, replay).
//
// Section content lives in `src/canvas/section-library/entries/*.json`
// (the pool). The composition references pool rows by their deterministic
// boot-upsert id (`${baseSlug}-v1`). Phase G deletes the whole-template
// JSON fixtures (`home.json`, `enterprise-scale.json`, `apogee-showcase.json`,
// `portfolio-showcase.json`) — the only remaining read of them here is
// the `customStyleKit` for `enterprise-scale-canvas`, `apogee-showcase`,
// and `portfolio-showcase`, which Phase G relocates.

import enterpriseScaleSeed from '../canvas/fixtures/enterprise-scale.json';
import apogeeShowcaseSeed from '../canvas/fixtures/apogee-showcase.json';
import portfolioShowcaseSeed from '../canvas/fixtures/portfolio-showcase.json';
import type {
  LoadExperience,
  MotionSequence,
  RichMotionAsset,
  ScrollScene,
} from '../canvas/behaviour-primitives.js';
import type {
  CanvasPage,
  CanvasSection,
  EditableSite,
  EditableSiteStyleKit,
  StyleKit,
  StyleKitPreset,
} from '../canvas/schema';
import {
  SECTION_LIBRARY,
  entryRowId,
  type SectionInstanceRef,
} from '../canvas/section-library/index.js';

/**
 * ADR 0061 Decision 6 — TemplateSeed shape.
 *
 * `pages[*]` mirrors `CanvasPage` except `sections` becomes `bodyRefs`
 * (pointers into the Section Library). `headerRef` / `footerRef` are
 * site-level pinned slots per ADR 0059.
 */
export interface TemplatePage extends Omit<CanvasPage, 'sections'> {
  bodyRefs: SectionInstanceRef[];
}

export interface TemplateSeed {
  id: string;
  name: string;
  tagline: string;
  styleKit: StyleKit;
  customStyleKit?: StyleKitPreset;
  headerRef?: SectionInstanceRef;
  footerRef?: SectionInstanceRef;
  loadExperience?: LoadExperience;
  motionSequences?: MotionSequence[];
  scrollScenes?: ScrollScene[];
  richMotionAssets?: RichMotionAsset[];
  pages: TemplatePage[];
}

// ---------------------------------------------------------------------------
// Section pool resolution
//
// Resolve refs against the entire SECTION_LIBRARY by deterministic
// `${baseSlug}-v${version}` id (Phase B's `entryRowId` shape). A miss is
// a build-time bug — fail loud rather than fall back to a placeholder.

const sectionPoolByRowId = new Map<string, (typeof SECTION_LIBRARY)[number]>();
for (const entry of SECTION_LIBRARY) {
  sectionPoolByRowId.set(entryRowId(entry), entry);
}

function resolveRef(ref: SectionInstanceRef): CanvasSection {
  const entry = sectionPoolByRowId.get(ref.sectionId);
  if (!entry) {
    throw new Error(
      `instantiateTemplate: unresolved section ref '${ref.sectionId}' — pool entry missing. ` +
        `Did you remove a ` +
        `SECTION_LIBRARY` +
        ` entry without updating the composition?`,
    );
  }
  // Deep clone so each instantiation gets a fresh tree; overrides + scope
  // never mutate the shared pool entry.
  const section = JSON.parse(JSON.stringify(entry.sectionData)) as CanvasSection;
  section.instanceScope = ref.instanceId;
  if (ref.overrides) {
    for (const [origId, patch] of Object.entries(ref.overrides)) {
      const el = section.elements.find((e) => e.id === origId);
      if (el) Object.assign(el, patch);
    }
  }
  return section;
}

// ---------------------------------------------------------------------------
// Template compositions
//
// Auto-generated by `scripts/gen-template-compositions.ts` at the Phase D
// rewrite. Hand-editable from here on; re-run the generator only as a
// reference if the underlying pool slugs ever get bulk-renamed.

const ENTERPRISE_KIT = (enterpriseScaleSeed as unknown as { customStyleKit: StyleKitPreset })
  .customStyleKit;
const APOGEE_KIT = (apogeeShowcaseSeed as unknown as { customStyleKit: StyleKitPreset })
  .customStyleKit;
const PORTFOLIO_KIT = (portfolioShowcaseSeed as unknown as { customStyleKit: StyleKitPreset })
  .customStyleKit;

export const starterTemplate: TemplateSeed = {
  id: 'starter-canvas',
  name: 'Starter Canvas',
  tagline:
    'A flexible canvas with editable sections, rich text, media, actions, shapes, surfaces, style kits, and motion.',
  styleKit: 'charcoal',
  headerRef: { sectionId: 'starter-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'starter-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Starter Canvas',
      width: 1440,
      bodyRefs: [
        { sectionId: 'starter-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'starter-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'starter-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const launchTemplate: TemplateSeed = {
  id: 'launch-canvas',
  name: 'Launch Page',
  tagline:
    'A crisp product-launch starting point with a strong hero, proof sections, and a direct CTA.',
  styleKit: 'blue-saas',
  headerRef: { sectionId: 'launch-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'launch-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Launch Page',
      width: 1440,
      bodyRefs: [
        { sectionId: 'launch-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'launch-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'launch-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const enterpriseScaleTemplate: TemplateSeed = {
  id: 'enterprise-scale-canvas',
  name: 'Enterprise Scale',
  tagline:
    'A proof-heavy enterprise landing page seed with governed launch messaging, outcome cards, team sections, scalability, and sales CTAs.',
  styleKit: 'custom',
  customStyleKit: ENTERPRISE_KIT,
  pages: [
    {
      id: 'page-enterprise-scale',
      slug: 'home',
      title: 'Enterprise Scale',
      width: 1440,
      bodyRefs: [
        { sectionId: 'enterprise-template-hero-v1', instanceId: 'enterprisehero' },
        { sectionId: 'enterprise-template-proof-v1', instanceId: 'enterpriseproof' },
        { sectionId: 'enterprise-template-outcomes-v1', instanceId: 'enterpriseoutcomes' },
        { sectionId: 'enterprise-template-teams-v1', instanceId: 'enterpriseteams' },
        { sectionId: 'enterprise-template-scale-v1', instanceId: 'enterprisescale' },
        { sectionId: 'enterprise-template-governance-v1', instanceId: 'enterprisegovernance' },
        { sectionId: 'enterprise-template-success-v1', instanceId: 'enterprisesuccess' },
      ],
    },
  ],
};

export const studioTemplate: TemplateSeed = {
  id: 'studio-canvas',
  name: 'Studio Portfolio',
  tagline:
    'A visual-first portfolio seed for studios, designers, photographers, and independent makers.',
  styleKit: 'orange-editorial',
  headerRef: { sectionId: 'studio-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'studio-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Studio Portfolio',
      width: 1440,
      bodyRefs: [
        { sectionId: 'studio-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'studio-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'studio-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const localTemplate: TemplateSeed = {
  id: 'local-canvas',
  name: 'Local Business',
  tagline:
    'A warm small-business seed for cafes, salons, classes, services, and neighborhood teams.',
  styleKit: 'green-organic',
  headerRef: { sectionId: 'local-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'local-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Local Business',
      width: 1440,
      bodyRefs: [
        { sectionId: 'local-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'local-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'local-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const pressTemplate: TemplateSeed = {
  id: 'press-canvas',
  name: 'Press Canvas',
  tagline:
    'A serif-led editorial canvas for writers, publications, and anyone who still believes a sentence can carry a brand.',
  styleKit: 'ivory-press',
  headerRef: { sectionId: 'press-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'press-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Press Canvas',
      width: 1440,
      bodyRefs: [
        { sectionId: 'press-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'press-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'press-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const violetLaunchTemplate: TemplateSeed = {
  id: 'violet-launch',
  name: 'Violet Launch',
  tagline:
    'A bold midnight launch canvas with electric violet accents — the look indie products take when they want to be noticed.',
  styleKit: 'midnight-violet',
  headerRef: { sectionId: 'violet-template-header-v1', instanceId: 'sectionheader' },
  footerRef: { sectionId: 'violet-template-footer-v1', instanceId: 'sectionfooter' },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Violet Launch',
      width: 1440,
      bodyRefs: [
        { sectionId: 'violet-template-hero-v1', instanceId: 'sectionhero' },
        { sectionId: 'violet-template-features-v1', instanceId: 'sectionfeatures' },
        { sectionId: 'violet-template-cta-v1', instanceId: 'sectioncta' },
      ],
    },
  ],
};

export const apogeeShowcaseTemplate: TemplateSeed = {
  id: 'apogee-showcase',
  name: 'Apogee Showcase',
  tagline:
    'A multi-page showcase site — dark, bold, and loaded with every element type. Carousels, charts, forms, code snippets, accordions, embeds, and more.',
  styleKit: 'custom',
  customStyleKit: APOGEE_KIT,
  headerRef: { sectionId: 'apogee-template-header-v1', instanceId: 'wfsiteheader' },
  footerRef: { sectionId: 'apogee-template-footer-v1', instanceId: 'wfsitefooter' },
  pages: [
    {
      id: 'page-wf-home',
      slug: 'index',
      title: 'Apogee - The web platform for modern businesses',
      width: 1440,
      description:
        'Design, build, optimize, and rank in AI search - all in Apogee. Enterprise-grade security, CMS, hosting, and AEO built in.',
      entranceAnimation: 'fade-up',
      scrollTriggerMode: 'on-scroll',
      bodyRefs: [
        { sectionId: 'apogee-template-hero-v1', instanceId: 'wfhero' },
        { sectionId: 'apogee-template-platform-v1', instanceId: 'wfplatform' },
        { sectionId: 'apogee-template-social-proof-v1', instanceId: 'wfsocialproof' },
        { sectionId: 'apogee-template-carousel-showcase-v1', instanceId: 'wfcarouselshowcase' },
        { sectionId: 'apogee-template-features-v1', instanceId: 'wffeatures' },
        { sectionId: 'apogee-template-cta-band-v1', instanceId: 'wfctaband' },
        { sectionId: 'apogee-template-embed-demo-v1', instanceId: 'wfembeddemo' },
      ],
    },
    {
      id: 'page-wf-blog',
      slug: 'blog',
      title: 'Blog - Insights, tutorials, and updates',
      width: 1440,
      description: 'The latest on web design, development, and building for the modern web.',
      entranceAnimation: 'fade-up',
      bodyRefs: [
        { sectionId: 'apogee-template-blog-hero-v1', instanceId: 'wfbloghero' },
        { sectionId: 'apogee-template-blog-featured-v1', instanceId: 'wfblogfeatured' },
        { sectionId: 'apogee-template-blog-collection-v1', instanceId: 'wfblogcollection' },
        { sectionId: 'apogee-template-blog-code-demo-v1', instanceId: 'wfblogcodedemo' },
        { sectionId: 'apogee-template-blog-newsletter-v1', instanceId: 'wfblognewsletter' },
      ],
    },
    {
      id: 'page-wf-pricing',
      slug: 'pricing',
      title: 'Pricing - Plans for every team',
      width: 1440,
      description:
        'Start building for free and add a paid plan later to unlock premium hosting, design, and collaboration features.',
      entranceAnimation: 'fade-up',
      bodyRefs: [
        { sectionId: 'apogee-template-pricing-hero-v1', instanceId: 'wfpricinghero' },
        { sectionId: 'apogee-template-pricing-tiers-v1', instanceId: 'wfpricingtiers' },
        { sectionId: 'apogee-template-pricing-compare-v1', instanceId: 'wfpricingcompare' },
        { sectionId: 'apogee-template-pricing-faq-v1', instanceId: 'wfpricingfaq' },
        { sectionId: 'apogee-template-pricing-chart-v1', instanceId: 'wfpricingchart' },
        { sectionId: 'apogee-template-pricing-cta-v1', instanceId: 'wfpricingcta' },
      ],
    },
    {
      id: 'page-wf-enterprise',
      slug: 'enterprise',
      title: 'Enterprise - Scale with confidence',
      width: 1440,
      description:
        'See how enterprises achieve a 332% ROI with Apogee. Enterprise-grade scalability, security, and support.',
      entranceAnimation: 'scale-in',
      scrollTriggerMode: 'on-scroll',
      bodyRefs: [
        { sectionId: 'apogee-template-ent-hero-v1', instanceId: 'wfenthero' },
        { sectionId: 'apogee-template-ent-pillars-v1', instanceId: 'wfentpillars' },
        { sectionId: 'apogee-template-ent-roi-chart-v1', instanceId: 'wfentroichart' },
        { sectionId: 'apogee-template-ent-demo-embed-v1', instanceId: 'wfentdemoembed' },
        { sectionId: 'apogee-template-ent-contact-form-v1', instanceId: 'wfentcontactform' },
        { sectionId: 'apogee-template-ent-logos-v1', instanceId: 'wfentlogos' },
        { sectionId: 'apogee-template-ent-cta-v1', instanceId: 'wfentcta' },
      ],
    },
    {
      id: 'page-wf-customers',
      slug: 'customers',
      title: 'Customers - Stories from 300,000+ teams',
      width: 1440,
      description:
        'See how enterprises, agencies, and businesses large and small build with Apogee.',
      entranceAnimation: 'fade-up',
      bodyRefs: [
        { sectionId: 'apogee-template-cust-hero-v1', instanceId: 'wfcusthero' },
        { sectionId: 'apogee-template-cust-carousel-v1', instanceId: 'wfcustcarousel' },
        { sectionId: 'apogee-template-cust-grid-v1', instanceId: 'wfcustgrid' },
        { sectionId: 'apogee-template-cust-cta-v1', instanceId: 'wfcustcta' },
      ],
    },
    {
      id: 'page-wf-404',
      slug: '_404',
      title: 'Lost in the wilds — Apogee',
      width: 1440,
      description: "We couldn't find that page. Head back home or browse the latest from Apogee.",
      entranceAnimation: 'fade-up',
      bodyRefs: [{ sectionId: 'apogee-template-404-hero-v1', instanceId: 'wf404hero' }],
    },
  ],
};

export const portfolioShowcaseTemplate: TemplateSeed = {
  id: 'portfolio-showcase',
  name: 'Engineer Portfolio',
  tagline:
    'Dark warm-toned single-page engineer portfolio: hero, tech stack, selected work, and a notes blog with four mock long-form posts that exercise the page-bound collection.',
  styleKit: 'custom',
  customStyleKit: PORTFOLIO_KIT,
  headerRef: { sectionId: 'portfolio-template-header-v1', instanceId: 'pfsiteheader' },
  footerRef: { sectionId: 'portfolio-template-footer-v1', instanceId: 'pfsitefooter' },
  pages: [
    {
      id: 'page-pf-home',
      slug: 'index',
      title: 'Aayushman Singh — Full-Stack Engineer',
      width: 1440,
      description:
        "Full-stack engineer building autonomous agents, developer tools, and production-grade web systems. SIH '24 winner with OSINT work deployed by India's National Investigation Agency.",
      entranceAnimation: 'fade-up',
      scrollTriggerMode: 'on-scroll',
      bodyRefs: [
        { sectionId: 'portfolio-template-hero-v1', instanceId: 'pfhero' },
        { sectionId: 'portfolio-template-explore-v1', instanceId: 'pfexplore' },
      ],
    },
    {
      // ADR 0063 dec 2 + F5 — `pageKind: 'collection-index'` is retired.
      // The Collection element inside the resolved
      // portfolio-template-blog-list section carries `collectionSlug:
      // 'blog'` directly (see the JSON), so this page no longer needs
      // page-level binding metadata. It is now an ordinary CanvasPage
      // whose body happens to include one Collection element bound to
      // the blog source.
      id: 'page-pf-blog',
      slug: 'blog',
      title: 'Notes — Aayushman Singh',
      width: 1440,
      description:
        'Long-form writing on autonomous agents, self-healing CI, local-first software, and building tools for the State.',
      entranceAnimation: 'fade-up',
      bodyRefs: [
        { sectionId: 'portfolio-template-blog-hero-v1', instanceId: 'pfbloghero' },
        { sectionId: 'portfolio-template-blog-list-v1', instanceId: 'pfbloglist' },
      ],
    },
    {
      // ADR 0060 F2 — single template page that materializes per collection
      // entry at publish time. Replaces the pre-F2 hand-authored
      // page-pf-post-* pages (post1..post4) that the portfolio composition
      // had at branch base. Section refs point at the new
      // `portfolio-template-post-tmpl-*` pool entries extracted from the
      // current portfolio-showcase.json fixture.
      id: 'page-pf-post-template',
      slug: 'blog/template',
      title: '{{title}}',
      width: 1440,
      description: '{{excerpt}}',
      locale: 'en',
      pageBackground: '#16140f',
      entranceAnimation: 'fade-up',
      defaultMotionPreset: 'fade-up',
      sectionGap: 0,
      maxWidth: 1440,
      pageKind: 'collection-item-template',
      collectionSlug: 'blog',
      bodyRefs: [
        { sectionId: 'portfolio-template-post-tmpl-hero-v1', instanceId: 'pfposttmplhero' },
        { sectionId: 'portfolio-template-post-tmpl-body-v1', instanceId: 'pfposttmplbody' },
      ],
    },
  ],
};

export const allTemplateSeeds: ReadonlyArray<TemplateSeed> = [
  starterTemplate,
  launchTemplate,
  enterpriseScaleTemplate,
  studioTemplate,
  localTemplate,
  pressTemplate,
  violetLaunchTemplate,
  apogeeShowcaseTemplate,
  portfolioShowcaseTemplate,
];

const templatesById = new Map(allTemplateSeeds.map((template) => [template.id, template]));

function cloneTemplateField<T>(value: T | undefined): T | undefined {
  return value === undefined ? undefined : structuredClone(value);
}

export function getTemplateSeed(id: string): TemplateSeed | null {
  return templatesById.get(id) ?? null;
}

/**
 * ADR 0061 Decision 6 — materialise a TemplateSeed composition into a
 * full `EditableSite`. Pages get their `bodyRefs` resolved against the
 * Section Library; header / footer get their refs resolved to the
 * `EditableSite.header` / `.footer` slots; customStyleKit / styleKit
 * pass through. Each materialised section carries `instanceScope` from
 * its ref's `instanceId` so the renderer can surface
 * `data-instance-scope` and Yjs round-trip preserves the binding.
 *
 * Throws on an unknown templateId or an unresolved section ref — both
 * are build-time mistakes, not runtime conditions.
 */
export function instantiateTemplate(templateId: string): EditableSite {
  const seed = templatesById.get(templateId);
  if (!seed) {
    throw new Error(`instantiateTemplate: unknown template id '${templateId}'`);
  }
  let styleKitField: EditableSiteStyleKit;
  if (seed.styleKit === 'custom') {
    if (seed.customStyleKit === undefined) {
      throw new Error(
        `instantiateTemplate: template '${templateId}' has styleKit='custom' but no customStyleKit`,
      );
    }
    styleKitField = { styleKit: 'custom', customStyleKit: seed.customStyleKit };
  } else {
    styleKitField = { styleKit: seed.styleKit };
  }
  const state: EditableSite = {
    ...styleKitField,
    pages: seed.pages.map((p) => {
      const page: CanvasPage = {
        id: p.id,
        slug: p.slug,
        title: p.title,
        width: p.width,
        sections: p.bodyRefs.map(resolveRef),
      };
      if (p.description !== undefined) page.description = p.description;
      if (p.ogImageAssetId !== undefined) page.ogImageAssetId = p.ogImageAssetId;
      if (p.canonical !== undefined) page.canonical = p.canonical;
      if (p.noIndex !== undefined) page.noIndex = p.noIndex;
      if (p.locale !== undefined) page.locale = p.locale;
      if (p.entranceAnimation !== undefined) page.entranceAnimation = p.entranceAnimation;
      if (p.scrollTriggerMode !== undefined) page.scrollTriggerMode = p.scrollTriggerMode;
      if (p.pageBackground !== undefined) page.pageBackground = p.pageBackground;
      if (p.defaultMotionPreset !== undefined) page.defaultMotionPreset = p.defaultMotionPreset;
      if (p.sectionGap !== undefined) page.sectionGap = p.sectionGap;
      if (p.maxWidth !== undefined) page.maxWidth = p.maxWidth;
      if (p.publishedDate !== undefined) page.publishedDate = p.publishedDate;
      if (p.author !== undefined) page.author = p.author;
      if (p.tags !== undefined) page.tags = p.tags;
      if (p.category !== undefined) page.category = p.category;
      if (p.suppressHeader !== undefined) page.suppressHeader = p.suppressHeader;
      if (p.suppressFooter !== undefined) page.suppressFooter = p.suppressFooter;
      if (p.pageKind !== undefined) page.pageKind = p.pageKind;
      if (p.collectionSlug !== undefined) page.collectionSlug = p.collectionSlug;
      return page;
    }),
  };
  if (seed.headerRef) state.header = resolveRef(seed.headerRef);
  if (seed.footerRef) state.footer = resolveRef(seed.footerRef);
  const loadExperience = cloneTemplateField(seed.loadExperience);
  const motionSequences = cloneTemplateField(seed.motionSequences);
  const scrollScenes = cloneTemplateField(seed.scrollScenes);
  const richMotionAssets = cloneTemplateField(seed.richMotionAssets);
  if (loadExperience !== undefined) state.loadExperience = loadExperience;
  if (motionSequences !== undefined) state.motionSequences = motionSequences;
  if (scrollScenes !== undefined) state.scrollScenes = scrollScenes;
  if (richMotionAssets !== undefined) state.richMotionAssets = richMotionAssets;
  return state;
}
