import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

import { contentHashToR2Key, extFromMediaType, sha256Hex } from '../../assets/hash.js';
import type { SeedAsset } from '../../canvas/seed-assets.js';
import type { ReplicaAssetSource, ReplicaSourcePackage } from './types.js';

export interface CompiledReplicaSeedAsset {
  seedId: string;
  sourceAsset: ReplicaAssetSource;
  registry: SeedAsset;
  base64SourcePath: string;
  base64: string;
}

function generatedSourcePath(seedId: string, mediaType: string): string {
  const ext = extFromMediaType(mediaType);
  const stem = seedId.startsWith('seed-') ? seedId.slice('seed-'.length) : seedId;
  return `${stem}.${ext}.b64`;
}

export async function compileReplicaSeedAssets(
  pkg: ReplicaSourcePackage,
): Promise<CompiledReplicaSeedAsset[]> {
  const compiled: CompiledReplicaSeedAsset[] = [];
  for (const sourceAsset of pkg.metadata.assets) {
    const rawPath = join(pkg.rootDir, 'assets', sourceAsset.sourcePath);
    let bytes: Uint8Array;
    try {
      bytes = await readFile(rawPath);
    } catch (cause) {
      throw new Error(`replica-assets: missing asset bytes ${sourceAsset.sourcePath}`, { cause });
    }
    const contentHash = await sha256Hex(bytes);
    const r2Key = contentHashToR2Key(contentHash, extFromMediaType(sourceAsset.mediaType));
    const sourcePath = generatedSourcePath(sourceAsset.id, sourceAsset.mediaType);
    compiled.push({
      seedId: sourceAsset.id,
      sourceAsset,
      base64SourcePath: sourcePath,
      base64: Buffer.from(bytes).toString('base64'),
      registry: {
        contentHash,
        r2Key,
        mediaType: sourceAsset.mediaType,
        kind: sourceAsset.kind,
        width: sourceAsset.width,
        height: sourceAsset.height,
        byteSize: bytes.byteLength,
        sourcePath,
        alt: sourceAsset.alt,
      },
    });
  }
  compiled.sort((a, b) => a.seedId.localeCompare(b.seedId));
  return compiled;
}

export function renderGeneratedSeedAssetRegistry(assets: CompiledReplicaSeedAsset[]): string {
  const lines: string[] = [];
  lines.push("import type { SeedAsset } from './seed-assets.js';");
  lines.push('');
  lines.push('// Generated by `bun run replica compile`. Do not edit by hand.');
  lines.push('export const GENERATED_SEED_ASSET_REGISTRY: Record<string, SeedAsset> = {');
  for (const asset of assets) {
    lines.push(`  ${JSON.stringify(asset.seedId)}: ${JSON.stringify(asset.registry, null, 2).replace(/\n/g, '\n  ')},`);
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}
