import { mkdir, readdir, rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import type { EditableSite, PublishedSnapshot } from '../../canvas/schema.js';
import { validateEditableSite, validatePublishedSnapshot } from '../../canvas/validate.js';
import { compileReplicaSeedAssets, renderGeneratedSeedAssetRegistry } from './assets.js';
import { loadReplicaPackage } from './load.js';
import type {
  ReplicaCompileReport,
  ReplicaCompileTarget,
  ReplicaPageSource,
  ReplicaSourcePackage,
} from './types.js';

export interface CompileReplicaPackageInput {
  sourceDir: string;
  target: ReplicaCompileTarget;
  repoRoot?: string;
  importOutDir?: string;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function instanceIdFor(baseSlug: string): string {
  const id = baseSlug.replace(/[^a-z0-9]/g, '');
  if (id.length === 0) throw new Error(`replica-compiler: cannot derive instance id for ${baseSlug}`);
  return id;
}

async function writeFileAtomic(filePath: string, content: string): Promise<void> {
  await mkdir(dirname(filePath), { recursive: true });
  const randomSuffix = Math.random().toString(36).slice(2, 8);
  const tmpPath = `${filePath}.${Date.now().toString(36)}.${process.pid}.${randomSuffix}.tmp`;
  await writeFile(tmpPath, content, 'utf8');
  await rename(tmpPath, filePath);
}

function renderTemplateSource(pkg: ReplicaSourcePackage): string {
  const lines: string[] = [];
  const exportName = `${pkg.metadata.id.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase())}Template`;
  lines.push("import type { TemplateSeed } from '../registry.js';");
  lines.push('');
  lines.push('// Generated by `bun run replica compile`. Do not edit by hand.');
  lines.push(`export const ${exportName}: TemplateSeed = {`);
  lines.push(`  id: ${quote(pkg.metadata.id)},`);
  lines.push(`  name: ${quote(pkg.metadata.name)},`);
  lines.push(`  tagline: ${quote(pkg.metadata.tagline)},`);
  lines.push(`  styleKit: ${quote(pkg.metadata.styleKit)},`);
  lines.push('  pages: [');
  for (const page of pkg.pages) {
    lines.push('    {');
    lines.push(`      id: ${quote(page.id)},`);
    lines.push(`      slug: ${quote(page.slug)},`);
    lines.push(`      title: ${quote(page.title)},`);
    lines.push(`      width: ${String(page.width)},`);
    if (page.description !== undefined) lines.push(`      description: ${quote(page.description)},`);
    if (page.pageBackground !== undefined) lines.push(`      pageBackground: ${quote(page.pageBackground)},`);
    if (page.sectionGap !== undefined) lines.push(`      sectionGap: ${String(page.sectionGap)},`);
    lines.push('      bodyRefs: [');
    for (const sectionSlug of page.sections) {
      lines.push(`        { sectionId: ${quote(`${sectionSlug}-v1`)}, instanceId: ${quote(instanceIdFor(sectionSlug))} },`);
    }
    lines.push('      ],');
    lines.push('    },');
  }
  lines.push('  ],');
  lines.push('};');
  lines.push('');
  lines.push(`export const generatedTemplateSeeds: ReadonlyArray<TemplateSeed> = [${exportName}];`);
  lines.push('');
  return lines.join('\n');
}

async function generateManifest(repoRoot: string): Promise<string> {
  const dirPath = join(repoRoot, 'src', 'templates', 'generated');
  const files = await readdir(dirPath);
  
  // Find all .ts files except manifest.ts and .d.ts files
  const templateFiles = files.filter(
    (file) => file.endsWith('.ts') && file !== 'manifest.ts' && !file.endsWith('.d.ts')
  );
  
  // Extract module names (strip .ts extension)
  const moduleNames = templateFiles.map((file) => file.slice(0, -3));
  
  // Sort module names deterministically
  moduleNames.sort();
  
  // Generate code
  const lines: string[] = [];
  lines.push("import type { TemplateSeed } from '../registry.js';");
  
  for (const mod of moduleNames) {
    const varName = `${mod.replace(/-/g, '_')}Templates`;
    lines.push(`import { generatedTemplateSeeds as ${varName} } from './${mod}.js';`);
  }
  
  lines.push('');
  lines.push('// Generated by `bun run replica compile`. Do not edit by hand.');
  
  const spreads = moduleNames.map((mod) => `...${mod.replace(/-/g, '_')}Templates`).join(', ');
  lines.push(`export const generatedTemplateSeeds: ReadonlyArray<TemplateSeed> = [${spreads}];`);
  lines.push('');
  
  return lines.join('\n');
}

function renderGeneratedSmokeSource(pkg: ReplicaSourcePackage): string {
  const requiredCopy = JSON.stringify(pkg.metadata.requiredCopy, null, 2);
  const requiredAssetIds = JSON.stringify(pkg.metadata.requiredAssetIds, null, 2);
  const forbidden = JSON.stringify(pkg.metadata.forbiddenRuntimeTokens, null, 2);
  const nativeEvidence = JSON.stringify(
    pkg.fidelityLedger.flatMap((item) => (item.status === 'native' ? (item.evidence ?? []) : [])),
    null,
    2,
  );
  const unsupportedIds = JSON.stringify(pkg.unsupported.map((item) => item.id), null, 2);
  return `import { renderBuiltInTemplatePreviewBodyHtml } from './built-in-preview.js';
import { getSeedAsset } from '../canvas/seed-assets.js';
import { validateEditableSite, validatePublishedSnapshot, validateSeedFixture } from '../canvas/validate.js';
import { getTemplateSeed, instantiateTemplate } from './registry.js';

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error('[${pkg.metadata.id}:replica-smoke] ' + message);
}

const seed = getTemplateSeed('${pkg.metadata.id}');
assert(seed !== null, 'getTemplateSeed(\\'${pkg.metadata.id}\\') must resolve generated template');

const state = instantiateTemplate('${pkg.metadata.id}');

const editable = validateEditableSite(state);
if (!editable.valid) {
  throw new Error('[${pkg.metadata.id}:replica-smoke] ' + editable.errors.join('\\\\n'));
}

const seedFixture = validateSeedFixture(state);
if (!seedFixture.valid) {
  throw new Error('[${pkg.metadata.id}:replica-smoke] ' + seedFixture.errors.join('\\\\n'));
}

const published = validatePublishedSnapshot({ ...state, version: 1, publishedAt: '2026-06-22T00:00:00.000Z' });
if (!published.valid) {
  throw new Error('[${pkg.metadata.id}:replica-smoke] ' + published.errors.join('\\\\n'));
}

const html = renderBuiltInTemplatePreviewBodyHtml('${pkg.metadata.id}', {
  turnstileSiteKey: '1x00000000000000000000AA',
});
for (const token of ${requiredCopy}) {
  assert(html.includes(token), 'preview must include required copy ' + JSON.stringify(token));
}
for (const assetId of ${requiredAssetIds}) {
  assert(getSeedAsset(assetId) !== null, 'seed asset must be registered ' + assetId);
  assert(html.includes(assetId), 'preview must include seed asset id ' + assetId);
}
for (const token of ${forbidden}) {
  assert(!html.toLowerCase().includes(String(token).toLowerCase()), 'preview must not include forbidden runtime token ' + token);
}
for (const token of ${nativeEvidence}) {
  assert(html.includes(token), 'native fidelity evidence missing ' + JSON.stringify(token));
}
for (const unsupportedId of ${unsupportedIds}) {
  assert(unsupportedId.length > 0, 'unsupported finding id must be non-empty');
}

console.log('[${pkg.metadata.id}:replica-smoke] OK');
`;
}

function materializePage(pkg: ReplicaSourcePackage, page: ReplicaPageSource): EditableSite['pages'][number] {
  return {
    id: page.id,
    slug: page.slug,
    title: page.title,
    width: page.width,
    ...(page.description !== undefined ? { description: page.description } : {}),
    ...(page.pageBackground !== undefined ? { pageBackground: page.pageBackground } : {}),
    ...(page.sectionGap !== undefined ? { sectionGap: page.sectionGap } : {}),
    sections: page.sections.map((sectionSlug) => {
      const entry = pkg.sections.find((section) => section.baseSlug === sectionSlug);
      if (!entry) throw new Error(`replica-compiler: missing section ${sectionSlug}`);
      const section = structuredClone(entry.sectionData);
      section.instanceScope = instanceIdFor(sectionSlug);
      return section;
    }),
  };
}

export function materializeReplicaEditableSite(pkg: ReplicaSourcePackage): EditableSite {
  const pages = pkg.pages.map((page) => materializePage(pkg, page));
  let site: EditableSite;

  if (pkg.metadata.styleKit === 'custom') {
    if (pkg.metadata.customStyleKit === undefined) {
      throw new Error("replica-compiler: custom style kit is required when styleKit is 'custom'");
    }
    site = {
      pages,
      styleKit: 'custom',
      customStyleKit: pkg.metadata.customStyleKit,
    };
  } else {
    site = {
      pages,
      styleKit: pkg.metadata.styleKit,
    };
  }

  const validation = validateEditableSite(site);
  if (!validation.valid) {
    throw new Error(`replica-compiler: import target produced invalid EditableSite:\n  ${validation.errors.join('\n  ')}`);
  }
  const snapshot: PublishedSnapshot = { ...site, version: 1, publishedAt: '2026-06-22T00:00:00.000Z' };
  const publishValidation = validatePublishedSnapshot(snapshot);
  if (!publishValidation.valid) {
    throw new Error(`replica-compiler: import target produced invalid PublishedSnapshot:\n  ${publishValidation.errors.join('\n  ')}`);
  }
  return site;
}

async function compileSeedTarget(pkg: ReplicaSourcePackage, repoRoot: string): Promise<string[]> {
  const written: string[] = [];
  const assets = await compileReplicaSeedAssets(pkg);
  for (const section of pkg.sections) {
    const path = join(repoRoot, 'src', 'canvas', 'section-library', 'entries', `${section.baseSlug}.json`);
    await writeFileAtomic(path, `${JSON.stringify(section, null, 2)}\n`);
    written.push(path);
  }
  for (const asset of assets) {
    const path = join(repoRoot, 'src', 'assets', 'seed-source', asset.base64SourcePath);
    await writeFileAtomic(path, `${asset.base64}\n`);
    written.push(path);
  }
  const seedRegistryPath = join(repoRoot, 'src', 'canvas', 'seed-assets.generated.ts');
  await writeFileAtomic(seedRegistryPath, renderGeneratedSeedAssetRegistry(assets));
  written.push(seedRegistryPath);
  const templatePath = join(repoRoot, 'src', 'templates', 'generated', `${pkg.metadata.id}.ts`);
  await writeFileAtomic(templatePath, renderTemplateSource(pkg));
  written.push(templatePath);
  const manifestPath = join(repoRoot, 'src', 'templates', 'generated', 'manifest.ts');
  await writeFileAtomic(manifestPath, await generateManifest(repoRoot));
  written.push(manifestPath);
  const smokePath = join(repoRoot, 'src', 'templates', `${pkg.metadata.id}.replica.smoke.ts`);
  await writeFileAtomic(smokePath, renderGeneratedSmokeSource(pkg));
  written.push(smokePath);
  return written;
}

async function compileImportTarget(pkg: ReplicaSourcePackage, importOutDir: string): Promise<{ written: string[]; site: EditableSite }> {
  const site = materializeReplicaEditableSite(pkg);
  const assets = await compileReplicaSeedAssets(pkg);
  const outDir = join(importOutDir, pkg.metadata.id);
  const written: string[] = [];
  const sitePath = join(outDir, 'editable-site.json');
  await writeFileAtomic(sitePath, `${JSON.stringify(site, null, 2)}\n`);
  written.push(sitePath);
  const manifestPath = join(outDir, 'asset-manifest.json');
  await writeFileAtomic(
    manifestPath,
    `${JSON.stringify(assets.map((asset) => ({ assetId: asset.seedId, ...asset.registry })), null, 2)}\n`,
  );
  written.push(manifestPath);
  return { written, site };
}

export async function compileReplicaPackage(
  input: CompileReplicaPackageInput,
): Promise<ReplicaCompileReport> {
  const repoRoot = input.repoRoot ?? process.cwd();
  const importOutDir = input.importOutDir ?? join(repoRoot, 'tmp', 'replicas');
  const pkg = await loadReplicaPackage(input.sourceDir);
  const target = input.target;
  if (target !== 'seed' && target !== 'import' && target !== 'both') {
    throw new Error(`replica-compiler: unsupported target ${String(target)}`);
  }
  const writtenFiles: string[] = [];
  let editableSite: EditableSite | undefined;
  if (target === 'seed' || target === 'both') {
    writtenFiles.push(...(await compileSeedTarget(pkg, repoRoot)));
  }
  if (target === 'import' || target === 'both') {
    const result = await compileImportTarget(pkg, importOutDir);
    writtenFiles.push(...result.written);
    editableSite = result.site;
  }
  const report: ReplicaCompileReport = {
    replicaId: pkg.metadata.id,
    target,
    writtenFiles,
    ...(editableSite !== undefined ? { editableSite } : {}),
    unsupported: pkg.unsupported,
    fidelityLedger: pkg.fidelityLedger,
  };
  if (target === 'import' || target === 'both') {
    const reportPath = join(importOutDir, pkg.metadata.id, 'report.json');
    await writeFileAtomic(reportPath, `${JSON.stringify({ ...report, editableSite: undefined }, null, 2)}\n`);
    report.writtenFiles.push(reportPath);
  }
  return report;
}
