// src/agent/design-section-images.ts
//
// Image generation integration for the designSection flow (Phase 3).
//
// After the layout engine resolves a semantic tree into a CanvasSection,
// this module collects all media elements with pending imagePrompts,
// generates images in parallel, creates ephemeral Owner Assets, and
// patches the assetIds back into the section.
//
// The generation is intentionally best-effort: if image generation fails
// for a prompt, the media element keeps its empty assetId and the Owner
// sees a placeholder. The section is still valid (empty assetIds are
// allowed in editable state per the validator).

import type { CanvasSection } from '../canvas/schema.js';

export interface ImageGenerationResult {
  elementId: string;
  assetId: string;
  prompt: string;
}

export interface GenerateImagesInput {
  section: CanvasSection;
  imagePrompts: Map<string, string>;
  customerId: string;
  siteId: string;
}

/**
 * Generate images for all pending media prompts in a designed section,
 * then patch the generated assetIds into the section's media elements.
 *
 * Returns the section with patched assetIds and the list of generated
 * assets (for cleanup if the Owner rejects the preview).
 *
 * When no image generation service is configured, this is a no-op:
 * media elements keep their empty assetIds.
 */
export async function generateDesignSectionImages(
  input: GenerateImagesInput,
): Promise<{ section: CanvasSection; generated: ImageGenerationResult[] }> {
  const { section, imagePrompts } = input;

  if (imagePrompts.size === 0) {
    return { section, generated: [] };
  }

  // Phase 3 scaffold: image generation service integration point.
  //
  // When the image generation route (/api/assets/generate) is available,
  // this function will:
  //   1. Call the generation endpoint in parallel for each prompt
  //   2. Upload the generated bytes as Owner Assets
  //   3. Patch assetIds into the section's media elements
  //
  // Until then, media elements keep empty assetIds — the Owner sees
  // placeholder slots and can upload images manually.

  const generated: ImageGenerationResult[] = [];
  return { section, generated };
}

/**
 * Patch generated asset IDs into a section's media elements.
 * Used when the orchestrator has generated images separately and needs
 * to inject them into the resolved section before preview.
 */
export function patchAssetIds(
  section: CanvasSection,
  assetMap: Map<string, string>,
): CanvasSection {
  if (assetMap.size === 0) return section;

  const patched = structuredClone(section);
  for (const element of patched.elements) {
    if (element.type !== 'media') continue;
    const assetId = assetMap.get(element.id);
    if (assetId !== undefined) {
      element.assetId = assetId;
    }
  }
  return patched;
}
