// src/canvas/section-library/origin-mapping.ts
//
// ADR 0061 Phase C — bridge between the pre-migration `(templateId,
// sectionId)` shape and the post-migration pool `baseSlug`. Auto-
// generated by `scripts/extract-section-library.ts`.
//
// Phase D's TemplateSeed composition rewrite resolves each old
// (templateId, sectionId) ref to its pool baseSlug via this table.
// Phase G prunes references once the rewrite lands; the table itself
// stays as a documented audit trail of which pool entry came from
// which template/section pair.

export const ORIGIN_TO_BASE_SLUG: Readonly<Record<string, string>> = {
  'apogee-showcase:wf-404-hero': 'apogee-template-404-hero',
  'apogee-showcase:wf-blog-code-demo': 'apogee-template-blog-code-demo',
  'apogee-showcase:wf-blog-collection': 'apogee-template-blog-collection',
  'apogee-showcase:wf-blog-featured': 'apogee-template-blog-featured',
  'apogee-showcase:wf-blog-hero': 'apogee-template-blog-hero',
  'apogee-showcase:wf-blog-newsletter': 'apogee-template-blog-newsletter',
  'apogee-showcase:wf-carousel-showcase': 'apogee-template-carousel-showcase',
  'apogee-showcase:wf-cta-band': 'apogee-template-cta-band',
  'apogee-showcase:wf-cust-carousel': 'apogee-template-cust-carousel',
  'apogee-showcase:wf-cust-cta': 'apogee-template-cust-cta',
  'apogee-showcase:wf-cust-grid': 'apogee-template-cust-grid',
  'apogee-showcase:wf-cust-hero': 'apogee-template-cust-hero',
  'apogee-showcase:wf-embed-demo': 'apogee-template-embed-demo',
  'apogee-showcase:wf-ent-contact-form': 'apogee-template-ent-contact-form',
  'apogee-showcase:wf-ent-cta': 'apogee-template-ent-cta',
  'apogee-showcase:wf-ent-demo-embed': 'apogee-template-ent-demo-embed',
  'apogee-showcase:wf-ent-hero': 'apogee-template-ent-hero',
  'apogee-showcase:wf-ent-logos': 'apogee-template-ent-logos',
  'apogee-showcase:wf-ent-pillars': 'apogee-template-ent-pillars',
  'apogee-showcase:wf-ent-roi-chart': 'apogee-template-ent-roi-chart',
  'apogee-showcase:wf-features': 'apogee-template-features',
  'apogee-showcase:wf-hero': 'apogee-template-hero',
  'apogee-showcase:wf-platform': 'apogee-template-platform',
  'apogee-showcase:wf-pricing-chart': 'apogee-template-pricing-chart',
  'apogee-showcase:wf-pricing-compare': 'apogee-template-pricing-compare',
  'apogee-showcase:wf-pricing-cta': 'apogee-template-pricing-cta',
  'apogee-showcase:wf-pricing-faq': 'apogee-template-pricing-faq',
  'apogee-showcase:wf-pricing-hero': 'apogee-template-pricing-hero',
  'apogee-showcase:wf-pricing-tiers': 'apogee-template-pricing-tiers',
  'apogee-showcase:wf-site-footer': 'apogee-template-footer',
  'apogee-showcase:wf-site-header': 'apogee-template-header',
  'apogee-showcase:wf-social-proof': 'apogee-template-social-proof',
  'enterprise-scale-canvas:enterprise-governance': 'enterprise-template-governance',
  'enterprise-scale-canvas:enterprise-hero': 'enterprise-template-hero',
  'enterprise-scale-canvas:enterprise-outcomes': 'enterprise-template-outcomes',
  'enterprise-scale-canvas:enterprise-proof': 'enterprise-template-proof',
  'enterprise-scale-canvas:enterprise-scale': 'enterprise-template-scale',
  'enterprise-scale-canvas:enterprise-success': 'enterprise-template-success',
  'enterprise-scale-canvas:enterprise-teams': 'enterprise-template-teams',
  'launch-canvas:section-cta': 'launch-template-cta',
  'launch-canvas:section-features': 'launch-template-features',
  'launch-canvas:section-footer': 'launch-template-footer',
  'launch-canvas:section-header': 'launch-template-header',
  'launch-canvas:section-hero': 'launch-template-hero',
  'local-canvas:section-cta': 'local-template-cta',
  'local-canvas:section-features': 'local-template-features',
  'local-canvas:section-footer': 'local-template-footer',
  'local-canvas:section-header': 'local-template-header',
  'local-canvas:section-hero': 'local-template-hero',
  'portfolio-showcase:pf-blog-hero': 'portfolio-template-blog-hero',
  'portfolio-showcase:pf-blog-list': 'portfolio-template-blog-list',
  'portfolio-showcase:pf-explore': 'portfolio-template-explore',
  'portfolio-showcase:pf-hero': 'portfolio-template-hero',
  'portfolio-showcase:pf-post1-body': 'portfolio-template-post1-body',
  'portfolio-showcase:pf-post1-hero': 'portfolio-template-post1-hero',
  'portfolio-showcase:pf-post2-body': 'portfolio-template-post2-body',
  'portfolio-showcase:pf-post2-hero': 'portfolio-template-post2-hero',
  'portfolio-showcase:pf-post3-body': 'portfolio-template-post3-body',
  'portfolio-showcase:pf-post3-hero': 'portfolio-template-post3-hero',
  'portfolio-showcase:pf-post4-body': 'portfolio-template-post4-body',
  'portfolio-showcase:pf-post4-hero': 'portfolio-template-post4-hero',
  'portfolio-showcase:pf-site-footer': 'portfolio-template-footer',
  'portfolio-showcase:pf-site-header': 'portfolio-template-header',
  'press-canvas:section-cta': 'press-template-cta',
  'press-canvas:section-features': 'press-template-features',
  'press-canvas:section-footer': 'press-template-footer',
  'press-canvas:section-header': 'press-template-header',
  'press-canvas:section-hero': 'press-template-hero',
  'starter-canvas:section-cta': 'starter-template-cta',
  'starter-canvas:section-features': 'starter-template-features',
  'starter-canvas:section-footer': 'starter-template-footer',
  'starter-canvas:section-header': 'starter-template-header',
  'starter-canvas:section-hero': 'starter-template-hero',
  'studio-canvas:section-cta': 'studio-template-cta',
  'studio-canvas:section-features': 'studio-template-features',
  'studio-canvas:section-footer': 'studio-template-footer',
  'studio-canvas:section-header': 'studio-template-header',
  'studio-canvas:section-hero': 'studio-template-hero',
  'violet-launch:section-cta': 'violet-template-cta',
  'violet-launch:section-features': 'violet-template-features',
  'violet-launch:section-footer': 'violet-template-footer',
  'violet-launch:section-header': 'violet-template-header',
  'violet-launch:section-hero': 'violet-template-hero',
};

export function resolveBaseSlug(templateId: string, sectionId: string): string {
  const key = `${templateId}:${sectionId}`;
  const slug = ORIGIN_TO_BASE_SLUG[key];
  if (slug === undefined) {
    throw new Error(`origin-mapping: no pool entry for ${key} — re-run scripts/extract-section-library.ts`);
  }
  return slug;
}
