// scripts/build-editor-client.ts
//
// ADR 0015 Phase 3 — Bun.build of src/editor-client/{index.ts, styles.css}
// into dist/_assets/index-<hash>.{js, css}. Writes the resolved URLs to
// src/_assets/manifest.generated.ts so the editor route consumes them as
// a typed import.
//
// Run:
//   bun run scripts/build-editor-client.ts            # production build
//   bun run scripts/build-editor-client.ts --dev      # dev build w/ inline
//                                                      sourcemaps + no minify
//
// Two-phase build:
//   1. Import canvasEditorStyles from src/editor-client/styles-build.ts
//      (a TS module that derives the chrome CSS from the per-kit registry
//      + theme tokens) and write the resolved string to
//      src/editor-client/styles.css. The CSS is regenerated on every
//      build so kit/theme changes propagate without manual file edits.
//   2. Run Bun.build against src/editor-client/index.ts; the entry's
//      `import './styles.css'` picks up the freshly-written CSS, and
//      Bun emits hashed JS + CSS sibling artifacts under dist/_assets/.
//
// Dev vs prod (ADR 0015 Decision 4):
//   - Dev (--dev): sourcemap = 'inline', minify = false. Browser dev
//     tools resolve errors to original TS files; the bundle is larger
//     but never reaches a real Owner.
//   - Prod (default): sourcemap = 'none', minify = true. No source leak
//     into the deployed Worker; cache-friendly minified output.
//
// Modelled on scripts/bundle-co-edit.ts — the existing Bun.build
// precedent in this repo. The output URL prefix is /_assets/ (matching
// the Wrangler [assets] binding from ADR 0015 decision 7).

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { canvasEditorStyles } from '../src/editor-client/styles-build.js';

const ROOT = resolve(import.meta.dirname, '..');
const OUT_DIR = resolve(ROOT, 'dist/_assets');
const HEADERS_PATH = resolve(ROOT, 'dist/_headers');
const MANIFEST_PATH = resolve(ROOT, 'src/_assets/manifest.generated.ts');
const STYLES_CSS_PATH = resolve(ROOT, 'src/editor-client/styles.css');
const ASSET_URL_PREFIX = '/_assets';

const isDev = process.argv.includes('--dev');

async function main(): Promise<void> {
  mkdirSync(OUT_DIR, { recursive: true });
  mkdirSync(resolve(ROOT, 'src/_assets'), { recursive: true });

  // Phase 1: resolve the TS-built CSS string to a file Bun.build can pick
  // up via the index.ts `import './styles.css'` statement. The file is a
  // build artifact even though it lives under src/ — committing it keeps
  // the repo self-contained for fork operators, mirroring the existing
  // src/_assets/manifest.generated.ts precedent.
  // The do-not-edit banner is intentionally loud — devtools-fixing-a-CSS-typo
  // here is a real footgun because the next editor-client:build clobbers the
  // file silently. Edits belong in styles-build.ts (or the upstream theme /
  // style-kit modules it composes).
  const cssHeader = `/* ============================================================== *\\
 *  AUTO-GENERATED — DO NOT EDIT THIS FILE BY HAND                  *
 *  Source of truth: src/editor-client/styles-build.ts              *
 *  Re-generate:     bun run editor-client:build                    *
 *  Any change you make here will be overwritten on the next build. *
\\* ============================================================== */
`;
  writeFileSync(STYLES_CSS_PATH, cssHeader + canvasEditorStyles, 'utf-8');

  // ADR 0015 Decision 3 — Workers Static Assets defaults to
  // `Cache-Control: public, max-age=0, must-revalidate, etag`. Content-hashed
  // filenames are byte-immutable by construction, so the `immutable`
  // directive is safe; a year of max-age + immutable removes the conditional
  // GET round-trip for repeat editor sessions. _headers syntax mirrors the
  // Cloudflare Pages convention; Workers Static Assets parses the same file
  // when it sits at the root of the assets directory.
  // https://developers.cloudflare.com/workers/static-assets/headers/
  const headersBody = `/_assets/*
  Cache-Control: public, max-age=31536000, immutable
`;
  writeFileSync(HEADERS_PATH, headersBody, 'utf-8');

  const result = await Bun.build({
    entrypoints: [resolve(ROOT, 'src/editor-client/index.ts')],
    outdir: OUT_DIR,
    target: 'browser',
    format: 'esm',
    minify: !isDev,
    naming: '[name]-[hash].[ext]',
    sourcemap: isDev ? 'inline' : 'none',
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error('Bun.build produced no successful output');
  }

  let canvasClientUrl: string | undefined;
  let canvasStylesUrl: string | undefined;

  for (const out of result.outputs) {
    const filename = out.path.split(/[\\/]/).pop();
    if (filename === undefined) continue;
    const url = `${ASSET_URL_PREFIX}/${filename}`;
    if (out.kind === 'entry-point') {
      canvasClientUrl = url;
    } else if (filename.endsWith('.css')) {
      canvasStylesUrl = url;
    }
  }

  if (canvasClientUrl === undefined) {
    throw new Error(
      'Bun.build emitted no entry-point JS artifact — check the entry import resolves',
    );
  }
  if (canvasStylesUrl === undefined) {
    throw new Error(
      'Bun.build emitted no CSS artifact — check src/editor-client/index.ts imports styles.css',
    );
  }

  // ADR 0020 Decision 1 (b) — co-edit, the largest pre-existing inline
  // script (~109 KB), ships as a separately-fetched hashed asset so it
  // drops out of the editor route's inline-script surface (eight scripts
  // → seven scripts). The remaining inline scripts are either small
  // static FOUC / chrome helpers shared with the dashboard route (which
  // ADR 0021 owns) or genuinely request-specific blobs that cannot
  // bundle. All seven get a CSP nonce per ADR 0020 decisions 1 and 2.
  // IIFE format mirrors scripts/bundle-co-edit.ts so the browser entry's
  // `window.__rev01CoEdit = { connectCoEdit }` assignment still lands at
  // load time without an ESM consumer.
  const coEditBuild = await Bun.build({
    entrypoints: [resolve(ROOT, 'src/live/co-edit/browser-entry.ts')],
    outdir: OUT_DIR,
    target: 'browser',
    format: 'iife',
    minify: !isDev,
    naming: 'co-edit-[hash].[ext]',
    sourcemap: isDev ? 'inline' : 'none',
  });

  if (!coEditBuild.success) {
    for (const log of coEditBuild.logs) console.error(log);
    throw new Error('Bun.build (co-edit) produced no successful output');
  }

  let coEditUrl: string | undefined;
  for (const out of coEditBuild.outputs) {
    const filename = out.path.split(/[\\/]/).pop();
    if (filename === undefined) continue;
    if (out.kind === 'entry-point') {
      coEditUrl = `${ASSET_URL_PREFIX}/${filename}`;
    }
  }
  if (coEditUrl === undefined) {
    throw new Error(
      'Bun.build emitted no co-edit entry-point JS artifact — check src/live/co-edit/browser-entry.ts',
    );
  }

  const manifestBody = `// Auto-generated by scripts/build-editor-client.ts — do not edit manually.
// Re-generate: bun run editor-client:build
//
// ADR 0015 editor-client manifest. Content-hashed URLs for the editor
// bundle. The hash changes when the bundle's source changes; identical
// source produces the same hash across builds, so the manifest is
// byte-stable when source is byte-stable.

export const EDITOR_CLIENT_MANIFEST = {
  canvasClientUrl: ${JSON.stringify(canvasClientUrl)},
  canvasStylesUrl: ${JSON.stringify(canvasStylesUrl)},
  coEditUrl: ${JSON.stringify(coEditUrl)},
} as const;
`;

  writeFileSync(MANIFEST_PATH, manifestBody, 'utf-8');
  const mode = isDev ? 'dev (inline sourcemaps, unminified)' : 'prod (minified, no sourcemaps)';
  console.log(`[build-editor-client] mode: ${mode}`);
  console.log(`[build-editor-client] wrote ${canvasClientUrl}`);
  console.log(`[build-editor-client] wrote ${canvasStylesUrl}`);
  console.log(`[build-editor-client] wrote ${coEditUrl}`);
  console.log(`[build-editor-client] wrote ${HEADERS_PATH} (immutable cache for /_assets/*)`);
  console.log(`[build-editor-client] manifest at ${MANIFEST_PATH}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
