// scripts/build-editor-client.ts
//
// ADR 0015 Phase 3 — Bun.build of src/editor-client/{index.ts, styles.css}
// into dist/_assets/index-<hash>.{js, css}. Writes the resolved URLs to
// src/_assets/manifest.generated.ts so the editor route consumes them as
// a typed import.
//
// Run: bun run scripts/build-editor-client.ts
//
// Two-phase build:
//   1. Import canvasEditorStyles from src/editor-client/styles-build.ts
//      (a TS module that derives the chrome CSS from the per-kit registry
//      + theme tokens) and write the resolved string to
//      src/editor-client/styles.css. The CSS is regenerated on every
//      build so kit/theme changes propagate without manual file edits.
//   2. Run Bun.build against src/editor-client/index.ts; the entry's
//      `import './styles.css'` picks up the freshly-written CSS, and
//      Bun emits hashed JS + CSS sibling artifacts under dist/_assets/.
//
// Modelled on scripts/bundle-co-edit.ts — the existing Bun.build
// precedent in this repo. The output URL prefix is /_assets/ (matching
// the Wrangler [assets] binding from ADR 0015 decision 7).

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { canvasEditorStyles } from '../src/editor-client/styles-build.js';

const ROOT = resolve(import.meta.dirname, '..');
const OUT_DIR = resolve(ROOT, 'dist/_assets');
const MANIFEST_PATH = resolve(ROOT, 'src/_assets/manifest.generated.ts');
const STYLES_CSS_PATH = resolve(ROOT, 'src/editor-client/styles.css');
const ASSET_URL_PREFIX = '/_assets';

async function main(): Promise<void> {
  mkdirSync(OUT_DIR, { recursive: true });
  mkdirSync(resolve(ROOT, 'src/_assets'), { recursive: true });

  // Phase 1: resolve the TS-built CSS string to a file Bun.build can pick
  // up via the index.ts `import './styles.css'` statement. The file is a
  // build artifact even though it lives under src/ — committing it keeps
  // the repo self-contained for fork operators, mirroring the existing
  // src/_assets/manifest.generated.ts precedent.
  const cssHeader = `/* Auto-generated by scripts/build-editor-client.ts — do not edit manually.
 * Re-generate: bun run editor-client:build
 *
 * Source of truth: src/editor-client/styles-build.ts
 */
`;
  writeFileSync(STYLES_CSS_PATH, cssHeader + canvasEditorStyles, 'utf-8');

  const result = await Bun.build({
    entrypoints: [resolve(ROOT, 'src/editor-client/index.ts')],
    outdir: OUT_DIR,
    target: 'browser',
    format: 'esm',
    minify: true,
    naming: '[name]-[hash].[ext]',
    sourcemap: 'none',
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error('Bun.build produced no successful output');
  }

  let canvasClientUrl: string | undefined;
  let canvasStylesUrl: string | undefined;

  for (const out of result.outputs) {
    const filename = out.path.split(/[\\/]/).pop();
    if (filename === undefined) continue;
    const url = `${ASSET_URL_PREFIX}/${filename}`;
    if (out.kind === 'entry-point') {
      canvasClientUrl = url;
    } else if (filename.endsWith('.css')) {
      canvasStylesUrl = url;
    }
  }

  if (canvasClientUrl === undefined) {
    throw new Error(
      'Bun.build emitted no entry-point JS artifact — check the entry import resolves',
    );
  }
  if (canvasStylesUrl === undefined) {
    throw new Error(
      'Bun.build emitted no CSS artifact — check src/editor-client/index.ts imports styles.css',
    );
  }

  const manifestBody = `// Auto-generated by scripts/build-editor-client.ts — do not edit manually.
// Re-generate: bun run editor-client:build
//
// ADR 0015 editor-client manifest. Content-hashed URLs for the editor
// bundle. The hash changes when the bundle's source changes; identical
// source produces the same hash across builds, so the manifest is
// byte-stable when source is byte-stable.

export const EDITOR_CLIENT_MANIFEST = {
  canvasClientUrl: ${JSON.stringify(canvasClientUrl)},
  canvasStylesUrl: ${JSON.stringify(canvasStylesUrl)},
} as const;
`;

  writeFileSync(MANIFEST_PATH, manifestBody, 'utf-8');
  console.log(`[build-editor-client] wrote ${canvasClientUrl}`);
  console.log(`[build-editor-client] wrote ${canvasStylesUrl}`);
  console.log(`[build-editor-client] manifest at ${MANIFEST_PATH}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
