// scripts/build-editor-client.ts
//
// ADR 0015 Phase 1 — Bun.build of src/editor-client/{index.ts, styles.css}
// into dist/_assets/index-<hash>.{js, css}. Writes the resolved URLs to
// src/_assets/manifest.generated.ts so the editor route (Phase 3+) can
// read them as a typed import instead of hardcoding hashes.
//
// Run: bun run scripts/build-editor-client.ts
//
// Modelled on scripts/bundle-co-edit.ts — the existing Bun.build
// precedent in this repo. Differences from that precedent:
//   - Writes hashed files to disk under dist/_assets/ rather than
//     bundling to a single string the editor route inlines. This is the
//     central shift ADR 0015 makes.
//   - Emits BOTH a JS entrypoint and its CSS sidecar, because Bun.build
//     handles `import './styles.css'` natively and writes the CSS as a
//     separate output artifact alongside the JS.
//   - The output URL prefix is /_assets/ (matching the Wrangler
//     [assets] binding ADR 0015 decision 7 will configure in Phase 2).

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const OUT_DIR = resolve(ROOT, 'dist/_assets');
const MANIFEST_PATH = resolve(ROOT, 'src/_assets/manifest.generated.ts');
const ASSET_URL_PREFIX = '/_assets';

async function main(): Promise<void> {
  mkdirSync(OUT_DIR, { recursive: true });
  mkdirSync(resolve(ROOT, 'src/_assets'), { recursive: true });

  const result = await Bun.build({
    entrypoints: [resolve(ROOT, 'src/editor-client/index.ts')],
    outdir: OUT_DIR,
    target: 'browser',
    format: 'esm',
    minify: true,
    naming: '[name]-[hash].[ext]',
    sourcemap: 'none',
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error('Bun.build produced no successful output');
  }

  let canvasClientUrl: string | undefined;
  let canvasStylesUrl: string | undefined;

  for (const out of result.outputs) {
    const filename = out.path.split(/[\\/]/).pop();
    if (filename === undefined) continue;
    const url = `${ASSET_URL_PREFIX}/${filename}`;
    if (out.kind === 'entry-point') {
      canvasClientUrl = url;
    } else if (filename.endsWith('.css')) {
      canvasStylesUrl = url;
    }
  }

  if (canvasClientUrl === undefined) {
    throw new Error(
      'Bun.build emitted no entry-point JS artifact — check the entry import resolves',
    );
  }
  if (canvasStylesUrl === undefined) {
    throw new Error(
      'Bun.build emitted no CSS artifact — check src/editor-client/index.ts imports styles.css',
    );
  }

  const manifestBody = `// Auto-generated by scripts/build-editor-client.ts — do not edit manually.
// Re-generate: bun run editor-client:build
//
// ADR 0015 editor-client manifest. Content-hashed URLs for the editor
// bundle. The hash changes when the bundle's source changes; identical
// source produces the same hash across builds, so the manifest is
// byte-stable when source is byte-stable.

export const EDITOR_CLIENT_MANIFEST = {
  canvasClientUrl: ${JSON.stringify(canvasClientUrl)},
  canvasStylesUrl: ${JSON.stringify(canvasStylesUrl)},
} as const;
`;

  writeFileSync(MANIFEST_PATH, manifestBody, 'utf-8');
  console.log(`[build-editor-client] wrote ${canvasClientUrl}`);
  console.log(`[build-editor-client] wrote ${canvasStylesUrl}`);
  console.log(`[build-editor-client] manifest at ${MANIFEST_PATH}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
