// scripts/bundle-co-edit.ts
//
// Bundles src/live/co-edit/browser-entry.ts (which re-exports connectCoEdit
// and attaches it to `window.__opencanvasCoEdit`) plus its Yjs / y-protocols deps
// into a single IIFE. The output is written to src/live/co-edit/bundled.ts as
// a string constant that the editor route injects via a <script> tag.
//
// Run: bun run scripts/bundle-co-edit.ts
//
// ADR 0015 follow-up: moved from esbuild (reaching into Wrangler's hoisted
// transitive) to Bun.build (built into the runtime, declared dependency
// surface, single bundler answer for the repo). Bun.build's IIFE format does
// not have an `esbuild --global-name` equivalent, so the `window.__opencanvasCoEdit
// = { connectCoEdit }` assignment lives in src/live/co-edit/browser-entry.ts
// rather than being injected by the bundler.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');

async function main(): Promise<void> {
  const result = await Bun.build({
    entrypoints: [resolve(ROOT, 'src/live/co-edit/browser-entry.ts')],
    target: 'browser',
    format: 'iife',
    minify: true,
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error('Bun.build produced no successful output');
  }

  const artifact = result.outputs[0];
  if (artifact === undefined) {
    throw new Error('Bun.build returned zero output artifacts');
  }
  const code = await artifact.text();

  const output = `// Auto-generated by scripts/bundle-co-edit.ts — do not edit manually.
// Re-generate: bun run scripts/bundle-co-edit.ts
export const CO_EDIT_BUNDLE = ${JSON.stringify(code)};
`;

  const outPath = resolve(ROOT, 'src/live/co-edit/bundled.ts');
  writeFileSync(outPath, output, 'utf-8');
  console.log(`Wrote ${String(code.length)} bytes to ${outPath}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
