// scripts/bundle-co-edit.ts
//
// Bundles src/live/co-edit/client.ts + Yjs + y-protocols into a single IIFE
// that exposes window.__rev01CoEdit = { connectCoEdit }. The output is written
// to src/live/co-edit/bundled.ts as a string constant that the editor route
// injects via a <script> tag.
//
// Run: npx tsx scripts/bundle-co-edit.ts

import { build } from 'esbuild';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

const ROOT = resolve(import.meta.dirname, '..');

async function main() {
  const result = await build({
    entryPoints: [resolve(ROOT, 'src/live/co-edit/client.ts')],
    bundle: true,
    format: 'iife',
    globalName: '__rev01CoEdit',
    platform: 'browser',
    target: ['es2020'],
    minify: true,
    write: false,
  });

  const code = result.outputFiles[0]?.text;
  if (!code) throw new Error('esbuild produced no output');

  const output = `// Auto-generated by scripts/bundle-co-edit.ts — do not edit manually.
// Re-generate: npx tsx scripts/bundle-co-edit.ts
export const CO_EDIT_BUNDLE = ${JSON.stringify(code)};
`;

  const outPath = resolve(ROOT, 'src/live/co-edit/bundled.ts');
  writeFileSync(outPath, output, 'utf-8');
  console.log(`Wrote ${code.length} bytes to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
