// scripts/gen-template-compositions.ts
//
// ADR 0061 Phase D — one-shot generator that prints the
// composition-shape `TemplateSeed` literal for every entry in
// `allTemplateSeeds`, derived from the *current* (pre-rewrite)
// `seed.state` + the Phase C origin map. The output is pasted into
// the rewritten `src/templates/registry.ts`; the script itself
// retires alongside the legacy fixtures in Phase G.
//
// Run with `bun run scripts/gen-template-compositions.ts > /tmp/compositions.ts`.

import type { EditableSite } from '../src/canvas/schema.js';
import { ORIGIN_TO_BASE_SLUG } from '../src/canvas/section-library/origin-mapping.js';
import { allTemplateSeeds } from '../src/templates/registry.js';

function entryRowId(baseSlug: string): string {
  return `${baseSlug}-v1`;
}

function instanceIdFor(rawId: string): string {
  const stripped = rawId.replace(/[^a-z0-9]/gi, '').toLowerCase();
  return stripped.length > 0 ? stripped : 'inst';
}

function refLiteral(templateId: string, sectionId: string): string {
  const slug = ORIGIN_TO_BASE_SLUG[`${templateId}:${sectionId}`];
  if (!slug) throw new Error(`no origin map slug for ${templateId}:${sectionId}`);
  return `{ sectionId: '${entryRowId(slug)}', instanceId: '${instanceIdFor(sectionId)}' }`;
}

function compositionLiteral(seed: { id: string; name: string; tagline: string; state: EditableSite }): string {
  const lines: string[] = [];
  lines.push('  {');
  lines.push(`    id: ${JSON.stringify(seed.id)},`);
  lines.push(`    name: ${JSON.stringify(seed.name)},`);
  lines.push(`    tagline: ${JSON.stringify(seed.tagline)},`);
  lines.push(`    styleKit: ${JSON.stringify(seed.state.styleKit)},`);
  if (seed.state.customStyleKit) {
    lines.push(`    customStyleKit: ${JSON.stringify(seed.state.customStyleKit)},`);
  }
  if (seed.state.header) {
    lines.push(`    headerRef: ${refLiteral(seed.id, seed.state.header.id)},`);
  }
  if (seed.state.footer) {
    lines.push(`    footerRef: ${refLiteral(seed.id, seed.state.footer.id)},`);
  }
  lines.push('    pages: [');
  for (const page of seed.state.pages) {
    lines.push('      {');
    lines.push(`        id: ${JSON.stringify(page.id)},`);
    lines.push(`        slug: ${JSON.stringify(page.slug)},`);
    lines.push(`        title: ${JSON.stringify(page.title)},`);
    if (page.width !== undefined) lines.push(`        width: ${String(page.width)},`);
    if (page.description !== undefined) lines.push(`        description: ${JSON.stringify(page.description)},`);
    if (page.entranceAnimation !== undefined) lines.push(`        entranceAnimation: ${JSON.stringify(page.entranceAnimation)},`);
    if (page.scrollTriggerMode !== undefined) lines.push(`        scrollTriggerMode: ${JSON.stringify(page.scrollTriggerMode)},`);
    if (page.suppressHeader === true) lines.push(`        suppressHeader: true,`);
    if (page.suppressFooter === true) lines.push(`        suppressFooter: true,`);
    if (page.password !== undefined) lines.push(`        password: ${JSON.stringify(page.password)},`);
    if (page.passwordExpiresAt !== undefined) lines.push(`        passwordExpiresAt: ${JSON.stringify(page.passwordExpiresAt)},`);
    lines.push('        bodyRefs: [');
    for (const section of page.sections) {
      lines.push(`          ${refLiteral(seed.id, section.id)},`);
    }
    lines.push('        ],');
    lines.push('      },');
  }
  lines.push('    ],');
  lines.push('  },');
  return lines.join('\n');
}

console.log('// AUTOGENERATED by scripts/gen-template-compositions.ts — paste into registry.ts');
console.log('export const TEMPLATE_COMPOSITIONS: readonly TemplateSeed[] = [');
for (const seed of allTemplateSeeds) {
  console.log(compositionLiteral(seed));
}
console.log('];');
