// scripts/manifest-helpers.ts
//
// Shared manifest read/write helpers used by both `build-editor-client.ts`
// and `build-dashboard-client.ts`. ADR 0015 (editor) and ADR 0021
// (dashboard) write into the same `src/_assets/manifest.generated.ts`
// export so the routes consume a single typed import — but the two
// builds run independently, so each must preserve the other's slots
// rather than overwrite them.
//
// The file's source-of-truth shape is one TS module exporting
// `EDITOR_CLIENT_MANIFEST` as a `const` object literal whose values are
// `/_assets/...` URLs. We parse the literal back into a record, merge
// the requested updates, write the literal back in a stable key order.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const KEY_ORDER = [
  'canvasClientUrl',
  'canvasStylesUrl',
  'coEditUrl',
  'dashboardClientUrl',
] as const;

const MANIFEST_HEADER = `// Auto-generated by scripts/build-editor-client.ts and
// scripts/build-dashboard-client.ts — do not edit manually.
// Re-generate: bun run editor-client:build (or dashboard-client:build).
//
// Per-bundle manifest. Content-hashed URLs for the editor + dashboard
// bundles served from the Wrangler [assets] binding. The hash changes
// when the bundle's source changes; identical source produces the same
// hash across builds, so the manifest is byte-stable when source is.

export const EDITOR_CLIENT_MANIFEST = {`;

export function readManifest(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const src = readFileSync(path, 'utf-8');
  const match = src.match(/EDITOR_CLIENT_MANIFEST = \{([\s\S]*?)\} as const;/);
  if (!match || match[1] === undefined) return {};
  const entries: Record<string, string> = {};
  for (const line of match[1].split('\n')) {
    const pair = line.match(/^\s*(\w+):\s*"([^"]+)",?\s*$/);
    if (pair && pair[1] !== undefined && pair[2] !== undefined) {
      entries[pair[1]] = pair[2];
    }
  }
  return entries;
}

export function writeManifest(path: string, updates: Record<string, string>): void {
  const existing = readManifest(path);
  const merged: Record<string, string> = { ...existing, ...updates };
  const entries = KEY_ORDER.filter((key) => merged[key] !== undefined)
    .map((key) => `  ${key}: ${JSON.stringify(merged[key])},`)
    .join('\n');
  writeFileSync(path, `${MANIFEST_HEADER}\n${entries}\n} as const;\n`, 'utf-8');
}
