import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

interface PackageJson {
  name?: string;
  version?: string;
  license?: string;
}

interface VendorPackage {
  packagePath: string[];
  expectedName: string;
  expectedVersion: string;
  licenseFile: string;
}

interface ResolvedVendorPackage {
  name: string;
  version: string;
  license: string;
  licenseText: string;
}

interface VendorBundle {
  bundleFile: string;
  entrypoint: string;
  exposedSymbol: string;
  exportName: string;
  generatedFile: string;
  globalName: string;
  packages: ResolvedVendorPackage[];
  tempPrefix: string;
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`[sync-interactive-vendors] ${message}`);
}

const repoRoot = resolve(import.meta.dir, '..');

async function readMitPackage(pkg: VendorPackage): Promise<ResolvedVendorPackage> {
  const packageDir = join(repoRoot, 'node_modules', ...pkg.packagePath);
  const packagePath = join(packageDir, 'package.json');
  const packageJson = JSON.parse(await readFile(packagePath, 'utf8')) as PackageJson;
  const licenseText = await readFile(join(packageDir, pkg.licenseFile), 'utf8');

  assert(
    packageJson.name === pkg.expectedName,
    `expected ${pkg.expectedName} package, got ${String(packageJson.name)}`,
  );
  assert(
    packageJson.version === pkg.expectedVersion,
    `expected ${pkg.expectedName}@${pkg.expectedVersion}, got ${String(packageJson.version)}`,
  );
  assert(
    packageJson.license === 'MIT',
    `expected ${pkg.expectedName} MIT license, got ${String(packageJson.license)}`,
  );
  assert(
    licenseText.includes('Permission is hereby granted') &&
      licenseText.includes('THE SOFTWARE IS PROVIDED "AS IS"'),
    `${pkg.expectedName} ${pkg.licenseFile} did not contain the expected MIT permission and warranty text`,
  );

  return {
    name: pkg.expectedName,
    version: pkg.expectedVersion,
    license: 'MIT',
    licenseText,
  };
}

function buildLicenseNotice(packages: ResolvedVendorPackage[]): string {
  return `/*!\n${packages
    .map((pkg) => `${pkg.name}@${pkg.version}\n\n${pkg.licenseText.trim()}`)
    .join('\n\n---\n\n')
    .replace(/\*\//g, '* /')}\n*/`;
}

async function writeVendorBundle(bundle: VendorBundle): Promise<void> {
  const tempDir = await mkdtemp(join(tmpdir(), bundle.tempPrefix));

  try {
    const result = await Bun.build({
      entrypoints: [bundle.entrypoint],
      outdir: tempDir,
      naming: bundle.bundleFile,
      format: 'iife',
      globalName: bundle.globalName,
      target: 'browser',
      minify: true,
      sourcemap: 'none',
    });

    if (!result.success) {
      for (const log of result.logs) console.error(log);
      throw new Error(`[sync-interactive-vendors] Bun failed to bundle ${bundle.bundleFile}`);
    }

    const bundledSource = await readFile(join(tempDir, bundle.bundleFile), 'utf8');
    assert(
      bundledSource.includes(bundle.exposedSymbol),
      `generated ${bundle.bundleFile} did not expose ${bundle.exposedSymbol}`,
    );

    const runtimeSource = `${buildLicenseNotice(bundle.packages)}\n${bundledSource}`;
    const packageSummary = bundle.packages
      .map((pkg) => `${pkg.name}@${pkg.version} (${pkg.license})`)
      .join(', ');
    const generated = [
      '// Generated by scripts/sync-interactive-vendors.ts. Do not edit by hand.',
      `// Source packages: ${packageSummary}.`,
      '// prettier-ignore',
      `export const ${bundle.exportName}: string = ${JSON.stringify(runtimeSource)};`,
      '',
    ].join('\n');

    await writeFile(bundle.generatedFile, generated, 'utf8');
    console.log(
      `[sync-interactive-vendors] wrote ${bundle.generatedFile} (${String(runtimeSource.length)} chars)`,
    );
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

const animePackage = await readMitPackage({
  packagePath: ['animejs'],
  expectedName: 'animejs',
  expectedVersion: '4.3.0',
  licenseFile: 'LICENSE.md',
});
const floatingDomPackage = await readMitPackage({
  packagePath: ['@floating-ui', 'dom'],
  expectedName: '@floating-ui/dom',
  expectedVersion: '1.7.6',
  licenseFile: 'LICENSE',
});
const floatingCorePackage = await readMitPackage({
  packagePath: ['@floating-ui', 'core'],
  expectedName: '@floating-ui/core',
  expectedVersion: '1.7.5',
  licenseFile: 'LICENSE',
});
const floatingUtilsPackage = await readMitPackage({
  packagePath: ['@floating-ui', 'utils'],
  expectedName: '@floating-ui/utils',
  expectedVersion: '0.2.11',
  licenseFile: 'LICENSE',
});
const lottiePackage = await readMitPackage({
  packagePath: ['lottie-web'],
  expectedName: 'lottie-web',
  expectedVersion: '5.13.0',
  licenseFile: 'LICENSE.md',
});

await writeVendorBundle({
  bundleFile: 'animejs-waapi.js',
  entrypoint: join(repoRoot, 'src', 'interactive', 'vendor', 'animejs-waapi-entry.ts'),
  exposedSymbol: '__opencanvasAnime',
  exportName: 'ANIMEJS_WAAPI_RUNTIME_SRC',
  generatedFile: join(repoRoot, 'src', 'interactive', 'vendor', 'animejs-waapi.generated.ts'),
  globalName: 'OpenCanvasAnime',
  packages: [animePackage],
  tempPrefix: 'opencanvas-animejs-',
});

await writeVendorBundle({
  bundleFile: 'floating-ui-dom.js',
  entrypoint: join(repoRoot, 'src', 'interactive', 'vendor', 'floating-ui-dom-entry.ts'),
  exposedSymbol: '__opencanvasFloating',
  exportName: 'FLOATING_UI_DOM_RUNTIME_SRC',
  generatedFile: join(repoRoot, 'src', 'interactive', 'vendor', 'floating-ui-dom.generated.ts'),
  globalName: 'OpenCanvasFloating',
  packages: [floatingDomPackage, floatingCorePackage, floatingUtilsPackage],
  tempPrefix: 'opencanvas-floating-ui-',
});

await writeVendorBundle({
  bundleFile: 'lottie-web-light.js',
  entrypoint: join(repoRoot, 'src', 'interactive', 'vendor', 'lottie-web-light-entry.ts'),
  exposedSymbol: '__opencanvasLottie',
  exportName: 'LOTTIE_WEB_LIGHT_RUNTIME_SRC',
  generatedFile: join(repoRoot, 'src', 'interactive', 'vendor', 'lottie-web-light.generated.ts'),
  globalName: 'OpenCanvasLottie',
  packages: [lottiePackage],
  tempPrefix: 'opencanvas-lottie-web-',
});
