// scripts/sync-brand-icons.ts
//
// Fetches a curated list of brand-mark SVGs from Simple Icons (CC0 public
// domain) and writes them into `src/canvas/icons/brand-icons.generated.ts`.
// The generated file is committed; this script is run by hand when the brand
// set changes — not part of the build.
//
// Background: ADR 0051 dec 2 ships 13 generic UI icons inline. Brand marks
// (github, linkedin, x, etc.) are trademarked. Simple Icons' path data is
// released CC0 (https://github.com/simple-icons/simple-icons/blob/develop/LICENSE.md)
// so vendoring its bytes is the cleanest path. This script does the vendoring.
//
// USAGE:
//   bun run scripts/sync-brand-icons.ts
//
// REQUIRES: network access to https://cdn.simpleicons.org/<slug>/
//
// The script is idempotent — running twice with the same SLUGS yields a
// byte-identical output file.

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

// Brand slugs to vendor. Order is alphabetical (output is deterministic).
// Add a slug here, re-run the script, commit the regenerated file. The slug
// matches Simple Icons' URL path: https://cdn.simpleicons.org/<slug>/.
const SLUGS = [
  'github',
  'linkedin',
  'x',
  'instagram',
  'facebook',
  'youtube',
  'discord',
  'mastodon',
  'bluesky',
  'medium',
  'substack',
  'rss',
] as const;

const OUT = 'src/canvas/icons/brand-icons.generated.ts';
const SOURCE = 'https://cdn.simpleicons.org';

interface FetchedIcon {
  slug: string;
  innerSvg: string; // The inner geometry (paths, etc.) — strips the wrapping <svg>.
}

export function stripSimpleIconInnerSvg(slug: string, svg: string): string {
  const opener = svg.indexOf('>');
  const closer = svg.lastIndexOf('</svg>');
  if (!svg.trimStart().startsWith('<svg') || opener < 0 || closer < 0 || closer <= opener) {
    throw new Error(`malformed SVG response for ${slug}: ${svg.slice(0, 120)}`);
  }
  const openingTag = svg.slice(0, opener + 1);
  if (!/\bviewBox=["']0 0 24 24["']/.test(openingTag)) {
    throw new Error(`malformed SVG response for ${slug}: expected viewBox="0 0 24 24"`);
  }
  const innerSvg = svg.slice(opener + 1, closer).trim();
  if (!/^<(path|g|circle|rect|polygon|polyline|line|ellipse)\b/.test(innerSvg)) {
    throw new Error(`malformed SVG response for ${slug}: expected SVG geometry`);
  }
  return innerSvg;
}

async function fetchOne(slug: string): Promise<FetchedIcon> {
  const url = `${SOURCE}/${slug}/`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`fetch ${url} failed: ${String(res.status)} ${res.statusText}`);
  }
  const svg = await res.text();
  // Simple Icons returns `<svg ...>...</svg>` where the inner content is the
  // brand mark geometry. Strip the wrapper here so renderIconSvg can wrap
  // with our standard attributes (viewBox, currentColor, etc.). Simple Icons'
  // viewBox is always "0 0 24 24" — same as our generic registry — so we can
  // splice the inner geometry straight into our wrapper without reprojecting.
  const innerSvg = stripSimpleIconInnerSvg(slug, svg);
  return { slug, innerSvg };
}

function emitFile(icons: FetchedIcon[]): string {
  const sorted = [...icons].sort((a, b) => a.slug.localeCompare(b.slug));
  const slugList = sorted.map((i) => `  '${i.slug}',`).join('\n');
  const pathEntries = sorted.map((i) => `  '${i.slug}': ${JSON.stringify(i.innerSvg)},`).join('\n');
  return [
    '// src/canvas/icons/brand-icons.generated.ts',
    '//',
    '// AUTOGENERATED by scripts/sync-brand-icons.ts — DO NOT EDIT BY HAND.',
    '// Re-run the script when the brand slug list changes.',
    '//',
    '// Source: Simple Icons (https://simpleicons.org) — released under CC0 1.0.',
    '// All path data here is in the public domain. The brand names themselves',
    '// remain the trademarks of their respective owners; vendoring the marks',
    '// is for the purpose of letting Owner sites link to those platforms.',
    '',
    'export const BRAND_ICON_SLUGS = [',
    slugList,
    '] as const;',
    'export type BrandIconSlug = (typeof BRAND_ICON_SLUGS)[number];',
    '',
    'export const BRAND_ICON_PATHS: Record<BrandIconSlug, string> = {',
    pathEntries,
    '};',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const icons: FetchedIcon[] = [];
  for (const slug of SLUGS) {
    process.stdout.write(`  fetch ${slug}... `);
    const icon = await fetchOne(slug);
    icons.push(icon);
    process.stdout.write(`${String(icon.innerSvg.length)} bytes\n`);
  }
  const out = emitFile(icons);
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, out);
  console.log(`wrote ${OUT}: ${String(icons.length)} brand icons`);
}

if (import.meta.main) {
  await main();
}
