// scripts/sync-section-library-manifest.ts
//
// ADR 0061 — composition-era manifest sync. Reads every committed
// `src/canvas/section-library/entries/*.json` file and regenerates
// `entries/manifest.ts`. Does not delete JSON files or rewrite
// `origin-mapping.ts` (that table stays as the legacy audit map).
//
// Run with `bun run section-library:sync` after adding or editing an
// entries/*.json file for a composition-era template.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const ENTRIES_DIR = join(ROOT, 'src/canvas/section-library/entries');
const MANIFEST_FILE = join(ENTRIES_DIR, 'manifest.ts');

interface ManifestEntryRef {
  baseSlug: string;
  filename: string;
}

function discoverEntries(): ManifestEntryRef[] {
  const refs: ManifestEntryRef[] = [];
  const seenSlugs = new Map<string, string>();

  for (const name of readdirSync(ENTRIES_DIR)) {
    if (!name.endsWith('.json')) continue;

    const filePath = join(ENTRIES_DIR, name);
    let parsed: unknown;
    try {
      parsed = JSON.parse(readFileSync(filePath, 'utf8'));
    } catch (cause) {
      throw new Error(`section-library:sync: entries/${name} is not valid JSON`, { cause });
    }

    if (typeof parsed !== 'object' || parsed === null) {
      throw new Error(`section-library:sync: entries/${name} must be a JSON object`);
    }

    const baseSlug = (parsed as { baseSlug?: unknown }).baseSlug;
    if (typeof baseSlug !== 'string' || baseSlug.length === 0) {
      throw new Error(`section-library:sync: entries/${name} is missing baseSlug`);
    }

    const previous = seenSlugs.get(baseSlug);
    if (previous !== undefined) {
      throw new Error(
        `section-library:sync: duplicate baseSlug "${baseSlug}" in entries/${previous} and entries/${name}`,
      );
    }
    seenSlugs.set(baseSlug, name);
    refs.push({ baseSlug, filename: name });
  }

  if (refs.length === 0) {
    throw new Error('section-library:sync: no entries/*.json files found');
  }

  return refs;
}

function manifestSource(refs: ManifestEntryRef[]): string {
  const sorted = [...refs].sort((a, b) => a.baseSlug.localeCompare(b.baseSlug));
  const importLines = sorted
    .map((e, i) => `import e${String(i)} from './${e.filename}' with { type: 'json' };`)
    .join('\n');
  const arrayLines = sorted.map((_, i) => `  e${String(i)} as SectionLibraryEntry,`).join('\n');
  return [
    '// src/canvas/section-library/entries/manifest.ts',
    '//',
    '// Auto-generated by `bun run section-library:sync`. Do not edit by hand —',
    '// re-run the sync command after adding or editing entries/*.json files.',
    '',
    "import type { SectionLibraryEntry } from '../types.js';",
    '',
    importLines,
    '',
    'export const EXTRACTED_ENTRIES: ReadonlyArray<SectionLibraryEntry> = [',
    arrayLines,
    '];',
    '',
  ].join('\n');
}

const refs = discoverEntries();
writeFileSync(MANIFEST_FILE, manifestSource(refs), 'utf8');

console.log(`section-library:sync: wrote ${String(refs.length)} entries to ${MANIFEST_FILE}`);
