import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

interface PackageJson {
  name?: string;
  version?: string;
  license?: string;
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`[sync-interactive-vendors] ${message}`);
}

const repoRoot = resolve(import.meta.dir, '..');
const animePackagePath = join(repoRoot, 'node_modules', 'animejs', 'package.json');
const animePackage = JSON.parse(await readFile(animePackagePath, 'utf8')) as PackageJson;
const animeLicensePath = join(repoRoot, 'node_modules', 'animejs', 'LICENSE.md');
const animeLicense = await readFile(animeLicensePath, 'utf8');

assert(
  animePackage.name === 'animejs',
  `expected animejs package, got ${String(animePackage.name)}`,
);
assert(
  animePackage.version === '4.3.0',
  `expected animejs@4.3.0, got ${String(animePackage.version)}`,
);
assert(
  animePackage.license === 'MIT',
  `expected animejs MIT license, got ${String(animePackage.license)}`,
);
assert(
  animeLicense.includes('Permission is hereby granted') &&
    animeLicense.includes('THE SOFTWARE IS PROVIDED "AS IS"'),
  'animejs LICENSE.md did not contain the expected MIT permission and warranty text',
);

const entrypoint = join(repoRoot, 'src', 'interactive', 'vendor', 'animejs-waapi-entry.ts');
const generatedPath = join(repoRoot, 'src', 'interactive', 'vendor', 'animejs-waapi.generated.ts');
const tempDir = await mkdtemp(join(tmpdir(), 'opencanvas-animejs-'));

try {
  const result = await Bun.build({
    entrypoints: [entrypoint],
    outdir: tempDir,
    naming: 'animejs-waapi.js',
    format: 'iife',
    globalName: 'OpenCanvasAnime',
    target: 'browser',
    minify: true,
    sourcemap: 'none',
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error('[sync-interactive-vendors] Bun failed to bundle animejs WAAPI runtime');
  }

  const bundle = await readFile(join(tempDir, 'animejs-waapi.js'), 'utf8');
  assert(
    bundle.includes('__opencanvasAnime'),
    'generated Anime.js adapter did not expose __opencanvasAnime',
  );

  const licenseNotice = `/*!\n${animeLicense.trim().replace(/\*\//g, '* /')}\n*/`;
  const runtimeSource = `${licenseNotice}\n${bundle}`;
  const generated = [
    '// Generated by scripts/sync-interactive-vendors.ts. Do not edit by hand.',
    `// Source package: animejs@${animePackage.version} (${animePackage.license}).`,
    '// prettier-ignore',
    `export const ANIMEJS_WAAPI_RUNTIME_SRC: string = ${JSON.stringify(runtimeSource)};`,
    '',
  ].join('\n');

  await writeFile(generatedPath, generated, 'utf8');
  console.log(
    `[sync-interactive-vendors] wrote ${generatedPath} (${String(runtimeSource.length)} chars)`,
  );
} finally {
  await rm(tempDir, { recursive: true, force: true });
}
