// src/canvas/section-library/entries/manifest.ts
//
// Auto-generated by `bun run section-library:sync`. Do not edit by hand —
// re-run the sync command after adding or editing entries/*.json files.

import type { SectionLibraryEntry } from '../types.js';

import e0 from './apogee-template-404-hero.json' with { type: 'json' };
import e1 from './apogee-template-blog-code-demo.json' with { type: 'json' };
import e2 from './apogee-template-blog-collection.json' with { type: 'json' };
import e3 from './apogee-template-blog-featured.json' with { type: 'json' };
import e4 from './apogee-template-blog-hero.json' with { type: 'json' };
import e5 from './apogee-template-blog-newsletter.json' with { type: 'json' };
import e6 from './apogee-template-carousel-showcase.json' with { type: 'json' };
import e7 from './apogee-template-cta-band.json' with { type: 'json' };
import e8 from './apogee-template-cust-carousel.json' with { type: 'json' };
import e9 from './apogee-template-cust-cta.json' with { type: 'json' };
import e10 from './apogee-template-cust-grid.json' with { type: 'json' };
import e11 from './apogee-template-cust-hero.json' with { type: 'json' };
import e12 from './apogee-template-embed-demo.json' with { type: 'json' };
import e13 from './apogee-template-ent-contact-form.json' with { type: 'json' };
import e14 from './apogee-template-ent-cta.json' with { type: 'json' };
import e15 from './apogee-template-ent-demo-embed.json' with { type: 'json' };
import e16 from './apogee-template-ent-hero.json' with { type: 'json' };
import e17 from './apogee-template-ent-logos.json' with { type: 'json' };
import e18 from './apogee-template-ent-pillars.json' with { type: 'json' };
import e19 from './apogee-template-ent-roi-chart.json' with { type: 'json' };
import e20 from './apogee-template-features.json' with { type: 'json' };
import e21 from './apogee-template-footer.json' with { type: 'json' };
import e22 from './apogee-template-header.json' with { type: 'json' };
import e23 from './apogee-template-hero.json' with { type: 'json' };
import e24 from './apogee-template-platform.json' with { type: 'json' };
import e25 from './apogee-template-pricing-chart.json' with { type: 'json' };
import e26 from './apogee-template-pricing-compare.json' with { type: 'json' };
import e27 from './apogee-template-pricing-cta.json' with { type: 'json' };
import e28 from './apogee-template-pricing-faq.json' with { type: 'json' };
import e29 from './apogee-template-pricing-hero.json' with { type: 'json' };
import e30 from './apogee-template-pricing-tiers.json' with { type: 'json' };
import e31 from './apogee-template-social-proof.json' with { type: 'json' };
import e32 from './enterprise-template-governance.json' with { type: 'json' };
import e33 from './enterprise-template-hero.json' with { type: 'json' };
import e34 from './enterprise-template-outcomes.json' with { type: 'json' };
import e35 from './enterprise-template-proof.json' with { type: 'json' };
import e36 from './enterprise-template-scale.json' with { type: 'json' };
import e37 from './enterprise-template-success.json' with { type: 'json' };
import e38 from './enterprise-template-teams.json' with { type: 'json' };
import e39 from './launch-template-cta.json' with { type: 'json' };
import e40 from './launch-template-features.json' with { type: 'json' };
import e41 from './launch-template-footer.json' with { type: 'json' };
import e42 from './launch-template-header.json' with { type: 'json' };
import e43 from './launch-template-hero.json' with { type: 'json' };
import e44 from './library-template-testimonial-cards.json' with { type: 'json' };
import e45 from './library-template-testimonial-quote.json' with { type: 'json' };
import e46 from './library-template-testimonial-video.json' with { type: 'json' };
import e47 from './local-template-cta.json' with { type: 'json' };
import e48 from './local-template-features.json' with { type: 'json' };
import e49 from './local-template-footer.json' with { type: 'json' };
import e50 from './local-template-header.json' with { type: 'json' };
import e51 from './local-template-hero.json' with { type: 'json' };
import e52 from './portfolio-template-blog-hero.json' with { type: 'json' };
import e53 from './portfolio-template-blog-list.json' with { type: 'json' };
import e54 from './portfolio-template-explore.json' with { type: 'json' };
import e55 from './portfolio-template-footer.json' with { type: 'json' };
import e56 from './portfolio-template-header.json' with { type: 'json' };
import e57 from './portfolio-template-hero.json' with { type: 'json' };
import e58 from './portfolio-template-post-tmpl-body.json' with { type: 'json' };
import e59 from './portfolio-template-post-tmpl-hero.json' with { type: 'json' };
import e60 from './portfolio-template-post1-body.json' with { type: 'json' };
import e61 from './portfolio-template-post1-hero.json' with { type: 'json' };
import e62 from './portfolio-template-post2-body.json' with { type: 'json' };
import e63 from './portfolio-template-post2-hero.json' with { type: 'json' };
import e64 from './portfolio-template-post3-body.json' with { type: 'json' };
import e65 from './portfolio-template-post3-hero.json' with { type: 'json' };
import e66 from './portfolio-template-post4-body.json' with { type: 'json' };
import e67 from './portfolio-template-post4-hero.json' with { type: 'json' };
import e68 from './press-template-cta.json' with { type: 'json' };
import e69 from './press-template-features.json' with { type: 'json' };
import e70 from './press-template-footer.json' with { type: 'json' };
import e71 from './press-template-header.json' with { type: 'json' };
import e72 from './press-template-hero.json' with { type: 'json' };
import e73 from './raydotsh-template-about.json' with { type: 'json' };
import e74 from './raydotsh-template-books.json' with { type: 'json' };
import e75 from './raydotsh-template-books-gallery.json' with { type: 'json' };
import e76 from './raydotsh-template-experience.json' with { type: 'json' };
import e77 from './raydotsh-template-footer.json' with { type: 'json' };
import e78 from './raydotsh-template-header.json' with { type: 'json' };
import e79 from './raydotsh-template-hero.json' with { type: 'json' };
import e80 from './raydotsh-template-software.json' with { type: 'json' };
import e81 from './starter-template-cta.json' with { type: 'json' };
import e82 from './starter-template-features.json' with { type: 'json' };
import e83 from './starter-template-footer.json' with { type: 'json' };
import e84 from './starter-template-header.json' with { type: 'json' };
import e85 from './starter-template-hero.json' with { type: 'json' };
import e86 from './studio-template-cta.json' with { type: 'json' };
import e87 from './studio-template-features.json' with { type: 'json' };
import e88 from './studio-template-footer.json' with { type: 'json' };
import e89 from './studio-template-header.json' with { type: 'json' };
import e90 from './studio-template-hero.json' with { type: 'json' };
import e91 from './tiny-replica-hero.json' with { type: 'json' };
import e92 from './velocity-template-artifacts.json' with { type: 'json' };
import e93 from './velocity-template-footer.json' with { type: 'json' };
import e94 from './velocity-template-header.json' with { type: 'json' };
import e95 from './velocity-template-hero.json' with { type: 'json' };
import e96 from './velocity-template-impact.json' with { type: 'json' };
import e97 from './velocity-template-store.json' with { type: 'json' };
import e98 from './velocity-template-story.json' with { type: 'json' };
import e99 from './violet-template-cta.json' with { type: 'json' };
import e100 from './violet-template-features.json' with { type: 'json' };
import e101 from './violet-template-footer.json' with { type: 'json' };
import e102 from './violet-template-header.json' with { type: 'json' };
import e103 from './violet-template-hero.json' with { type: 'json' };

export const EXTRACTED_ENTRIES: ReadonlyArray<SectionLibraryEntry> = [
  e0 as SectionLibraryEntry,
  e1 as SectionLibraryEntry,
  e2 as SectionLibraryEntry,
  e3 as SectionLibraryEntry,
  e4 as SectionLibraryEntry,
  e5 as SectionLibraryEntry,
  e6 as SectionLibraryEntry,
  e7 as SectionLibraryEntry,
  e8 as SectionLibraryEntry,
  e9 as SectionLibraryEntry,
  e10 as SectionLibraryEntry,
  e11 as SectionLibraryEntry,
  e12 as SectionLibraryEntry,
  e13 as SectionLibraryEntry,
  e14 as SectionLibraryEntry,
  e15 as SectionLibraryEntry,
  e16 as SectionLibraryEntry,
  e17 as SectionLibraryEntry,
  e18 as SectionLibraryEntry,
  e19 as SectionLibraryEntry,
  e20 as SectionLibraryEntry,
  e21 as SectionLibraryEntry,
  e22 as SectionLibraryEntry,
  e23 as SectionLibraryEntry,
  e24 as SectionLibraryEntry,
  e25 as SectionLibraryEntry,
  e26 as SectionLibraryEntry,
  e27 as SectionLibraryEntry,
  e28 as SectionLibraryEntry,
  e29 as SectionLibraryEntry,
  e30 as SectionLibraryEntry,
  e31 as SectionLibraryEntry,
  e32 as SectionLibraryEntry,
  e33 as SectionLibraryEntry,
  e34 as SectionLibraryEntry,
  e35 as SectionLibraryEntry,
  e36 as SectionLibraryEntry,
  e37 as SectionLibraryEntry,
  e38 as SectionLibraryEntry,
  e39 as SectionLibraryEntry,
  e40 as SectionLibraryEntry,
  e41 as SectionLibraryEntry,
  e42 as SectionLibraryEntry,
  e43 as SectionLibraryEntry,
  e44 as SectionLibraryEntry,
  e45 as SectionLibraryEntry,
  e46 as SectionLibraryEntry,
  e47 as SectionLibraryEntry,
  e48 as SectionLibraryEntry,
  e49 as SectionLibraryEntry,
  e50 as SectionLibraryEntry,
  e51 as SectionLibraryEntry,
  e52 as SectionLibraryEntry,
  e53 as SectionLibraryEntry,
  e54 as SectionLibraryEntry,
  e55 as SectionLibraryEntry,
  e56 as SectionLibraryEntry,
  e57 as SectionLibraryEntry,
  e58 as SectionLibraryEntry,
  e59 as SectionLibraryEntry,
  e60 as SectionLibraryEntry,
  e61 as SectionLibraryEntry,
  e62 as SectionLibraryEntry,
  e63 as SectionLibraryEntry,
  e64 as SectionLibraryEntry,
  e65 as SectionLibraryEntry,
  e66 as SectionLibraryEntry,
  e67 as SectionLibraryEntry,
  e68 as SectionLibraryEntry,
  e69 as SectionLibraryEntry,
  e70 as SectionLibraryEntry,
  e71 as SectionLibraryEntry,
  e72 as SectionLibraryEntry,
  e73 as SectionLibraryEntry,
  e74 as SectionLibraryEntry,
  e75 as SectionLibraryEntry,
  e76 as SectionLibraryEntry,
  e77 as SectionLibraryEntry,
  e78 as SectionLibraryEntry,
  e79 as SectionLibraryEntry,
  e80 as SectionLibraryEntry,
  e81 as SectionLibraryEntry,
  e82 as SectionLibraryEntry,
  e83 as SectionLibraryEntry,
  e84 as SectionLibraryEntry,
  e85 as SectionLibraryEntry,
  e86 as SectionLibraryEntry,
  e87 as SectionLibraryEntry,
  e88 as SectionLibraryEntry,
  e89 as SectionLibraryEntry,
  e90 as SectionLibraryEntry,
  e91 as SectionLibraryEntry,
  e92 as SectionLibraryEntry,
  e93 as SectionLibraryEntry,
  e94 as SectionLibraryEntry,
  e95 as SectionLibraryEntry,
  e96 as SectionLibraryEntry,
  e97 as SectionLibraryEntry,
  e98 as SectionLibraryEntry,
  e99 as SectionLibraryEntry,
  e100 as SectionLibraryEntry,
  e101 as SectionLibraryEntry,
  e102 as SectionLibraryEntry,
  e103 as SectionLibraryEntry,
];
