// src/canvas/icons.ts
//
// Inline-SVG icon registry — system primitives that live at build time, not
// in R2. Each entry is a simple geometric composition I author here from
// SVG drawing operations (rects, lines, paths, arcs). All icons share one
// 24x24 viewBox + a stroke-currentColor wrapper so they inherit text colour
// when placed inside a button label and respect the active style kit.
//
// Two consumers:
//   - ActionElement.iconKind   → inline before label runs (1em sizing)
//   - ShapeElement.variant 'icon' + iconKind  → decorative, fills the box
//
// Adding a new icon:
//   1. Add the name to ICON_NAMES.
//   2. Add the inner SVG markup to ICON_PATHS.
//   3. Update the validate-parity smoke if it pins the icon set size.
// The rule for adding a new icon is "the same icon is requested in two or
// more templates" — single-template requests stay in fixture pinnedStyle
// until a second request lands. ADR 0051 dec 2.
//
// Brand marks (github / linkedin / x and friends) intentionally NOT in this
// generic set. They land via the optional brand-icon registry generated by
// `scripts/sync-brand-icons.ts` (Simple Icons CC0 public domain) when a
// template needs them. Until that script is run + the generated file
// committed, brand icons are not available — see ADR 0051 dec 2 "Why brand
// icons are NOT in the initial set."
//
// To enable brand icons:
//   1. `bun run scripts/sync-brand-icons.ts` (requires network).
//   2. The script writes `src/canvas/icons/brand-icons.generated.ts`.
//   3. Add a thin re-export here (or accept the resulting `BrandIconSlug`
//      union as a sibling of `IconName`, queried via `isBrandIconSlug`).
// The generic set ships unchanged; brand support is purely additive.

import { escapeAttr } from './elements/render-utils.js';

export const ICON_NAMES = [
  'mail',
  'copy',
  'check',
  'arrow-up-right',
  'arrow-left',
  'download',
  'external',
  'chevron-down',
  'menu',
  'close',
  'plus',
  'minus',
  'search',
] as const;
export type IconName = (typeof ICON_NAMES)[number];

/**
 * Inner SVG markup for each icon. The wrapper (<svg viewBox=… stroke=…>) is
 * added by `renderIconSvg`; entries here hold only the geometry so the
 * wrapper attributes stay consistent across the registry.
 *
 * All paths are designed against a 24x24 viewBox with stroke-width 2 and
 * `stroke-linecap="round"`, `stroke-linejoin="round"`. None are fill-based.
 */
const ICON_PATHS: Record<IconName, string> = {
  // Envelope: outer rect + flap triangle inside.
  mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/>',

  // Two stacked rounded rectangles, the back one offset up-left.
  copy: '<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>',

  // Checkmark V-stroke.
  check: '<path d="M20 6L9 17l-5-5"/>',

  // Arrow exiting up-and-right.
  'arrow-up-right': '<path d="M7 17L17 7M17 7H8M17 7v9"/>',

  // Arrow pointing left.
  'arrow-left': '<path d="M19 12H5M12 19l-7-7 7-7"/>',

  // Down arrow into an open tray.
  download: '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/>',

  // Box with arrow exiting upper-right corner.
  external:
    '<path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6M15 3h6v6M10 14L21 3"/>',

  // Single downward chevron.
  'chevron-down': '<path d="M6 9l6 6 6-6"/>',

  // Three horizontal hamburger lines.
  menu: '<path d="M3 12h18M3 6h18M3 18h18"/>',

  // Two diagonal strokes forming an X.
  close: '<path d="M18 6L6 18M6 6l12 12"/>',

  // Plus sign.
  plus: '<path d="M12 5v14M5 12h14"/>',

  // Horizontal line.
  minus: '<path d="M5 12h14"/>',

  // Magnifying glass — circle + diagonal handle.
  search: '<circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/>',
};

/**
 * Render an icon as an inline `<svg>` string. `inline` (default true) sizes
 * the icon at `1em × 1em` so it scales with the surrounding font; pass
 * `inline: false` to fill the element box instead (used by ShapeElement
 * variant 'icon' where the icon is the entire positioned element).
 *
 * The icon inherits its stroke colour from `currentColor`, so the surrounding
 * text colour (kit `color`, pinned style override, etc.) drives it.
 *
 * Throws when `name` is not in `ICON_NAMES`. The renderer is the only throw
 * site in the canvas subsystem (ADR 0025); validators guarantee that any
 * `IconName` reaching here is one of the registered keys.
 */
export function renderIconSvg(name: IconName, opts: { inline?: boolean } = {}): string {
  const inner = ICON_PATHS[name];
  if (inner === undefined) {
    throw new Error(`renderIconSvg: unknown icon "${String(name)}"`);
  }
  const inline = opts.inline ?? true;
  const sizeAttrs = inline ? 'width="1em" height="1em"' : 'width="100%" height="100%"';
  return `<svg class="opencanvas-icon" data-opencanvas-icon="${escapeAttr(name)}" viewBox="0 0 24 24" ${sizeAttrs} fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${inner}</svg>`;
}

export function isIconName(value: unknown): value is IconName {
  return typeof value === 'string' && (ICON_NAMES as readonly string[]).includes(value);
}
